# ------------------------------------------------------------------------------
# --- Configuration page de création de client
# ------------------------------------------------------------------------------
# Paramètres
[params]
tab = "Clients"
styles = ["css/customer/customer.css", "css/main.css"]
modules = ["js/customer/customer.js", "js/main.js"]
# Clées
[meta]
title = "Nouveau client | Intranet"
description = "Page de création d'un nouveau client dans l'intranet"
keywords = "client, création, formulaire"
author = "Rémi Verschuur"
robots = "noindex, nofollow"
[meta.accessibility]
lang="fr"
direction="ltr"
aria_role="document"
# Pages spécifiques
[layout]
main_layout = "customer/create.html"
extend_layout = "index.html"
# Flags
[flags]
navbar = true
searchbar = false
userbar = true
