# ------------------------------------------------------------------------------
# --- Configuration page d'accueil des clients
# ------------------------------------------------------------------------------
# Paramètres
[params]
tab = "Clients"
styles = ["css/customer/customer.css", "css/main.css"]
modules = ["js/customer/index.js", "js/main.js"]
# Clées
[meta]
title = "Accueil clients | Intranet"
description = "Page d'accueil du module client dans l'intranet"
keywords = "client, accueil, module"
author = "Rémi Verschuur"
robots = "noindex, nofollow"
[meta.accessibility]
lang="fr"
direction="ltr"
aria_role="document"
# Pages spécifiques
[layout]
main_layout = "customer/index.html"
extend_layout = "index.html"
# Flags
[flags]
navbar = true
searchbar = false
userbar = true