"""Migration initiale

Revision ID: 20333e4bb49a
Revises: 2026-02-16 11:21:55.000000
Create Date: 2026-02-16 10:55:25.736825
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20333e4bb49a'
down_revision: Union[str, Sequence[str], None] = '2026-02-16 11:21:55.000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

LAST_SYNC = 'Dernière synchronisation'
SOURCE_SYNC = 'Source de la dernière mise à jour'
CUSTOMER_PK = "app_schema.customers.id"
CUSTOMER_ADDRESS_PK = "app_schema.customer_addresses.id"
GENERAL_OBJECT_PK = "app_schema.general_objects.id"
INVOICE_PK = "app_schema.invoices.id"
ORDER_PK = "app_schema.orders.id"
SHIPMENT_PK = "app_schema.shipments.id"

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',    # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment='Identifiant unique du client'),
        sa.Column('wpwc_id', sa.String(length=50), nullable=True,
                  comment='Identifiant WooCommerce'),
        sa.Column('henrri_id', sa.String(length=100), nullable=True,
                  comment='Identifiant Henrri'),
        sa.Column('customer_type', sa.String(length=20), nullable=False,
                  comment='Type de client : part/pro'),
        sa.Column('is_active', sa.Boolean(), nullable=False,
                  comment='Statut actif/inactif du client'),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment='Date de création du client'),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment='Date de dernière mise à jour du client'),
        sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment=LAST_SYNC),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('henrri_id'),
        sa.UniqueConstraint('wpwc_id'),
        schema='app_schema'
    )
    op.create_table('invoices', # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('reference', sa.String(length=14), nullable=False),
        sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False,
                  comment='Montant total de la facture'),
        sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=False,
                  comment='Montant de la TVA de la facture'),
        sa.Column('create_source', sa.String(length=50), nullable=False,
                  comment='Source de la facture'),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment='Date de création de la facture'),
        sa.Column('update_source', sa.String(length=50), nullable=True,comment=SOURCE_SYNC),
        sa.Column('updated_at', sa.DateTime(), nullable=True,
                  comment='Date dernière mise à jour de la facture'),
        sa.Column('last_synced_at', sa.DateTime(), nullable=True,
                  comment=LAST_SYNC),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('reference'),
        schema='app_schema'
    )
    op.create_table('shipments',    # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('reference', sa.String(length=14), nullable=False),
        sa.Column('carrier', sa.String(length=50), nullable=False),
        sa.Column('tracking_number', sa.String(length=50), nullable=True),
        sa.Column('create_source', sa.String(length=50), nullable=False,
                  comment="Source de l'envoi"),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment="Date de création de l'envoi"),
        sa.Column('update_source', sa.String(length=50), nullable=True,
                  comment=SOURCE_SYNC),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment="Date dernière mise à jour de l'envoi"),
        sa.Column('last_synced_at', sa.DateTime(), nullable=True,
                  comment=LAST_SYNC),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('reference'),
        schema='app_schema'
    )
    op.create_table('suppliers',    # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment='Identifiant unique du fournisseur'),
        sa.Column('name', sa.String(), nullable=False, comment='Nom du fournisseur'),
        sa.Column('contact_phone', sa.String(), nullable=False,
                  comment='Téléphone de contact du fournisseur'),
        sa.Column('contact_email', sa.String(), nullable=False,
                  comment='Email de contact du fournisseur'),
        sa.Column('is_active', sa.Boolean(), nullable=False,
                  comment='Indique si le fournisseur est actif'),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment='Date de création du fournisseur'),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment='Date de dernière MàJ du fournisseur'),
        sa.PrimaryKeyConstraint('id'),
        schema='app_schema'
    )
    op.create_table('tags',   # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment='Identifiant unique du tag'),
        sa.Column('name', sa.String(), nullable=False, comment='Nom du tag'),
        sa.Column('description', sa.String(), nullable=False,
                  comment='Description du tag'),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment='Date de création du tag'),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment='Date de dernière MàJ du tag'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        schema='app_schema'
    )
    op.create_table('customer_addresses',   # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                comment='Identifiant unique'),
        sa.Column('customer_id', sa.Integer(), nullable=False,
                comment='Identifiant du client associé'),
        sa.Column('address_name', sa.String(length=100), nullable=True,
                comment="Nom d'adresse (ex: home, work)"),
        sa.Column('address_line1', sa.String(length=200), nullable=False,
                comment="Ligne d'adresse 1"),
        sa.Column('address_line2', sa.String(length=200), nullable=True,
                comment="Ligne d'adresse 2"),
        sa.Column('city', sa.String(length=100), nullable=False,
                comment='Ville'),
        sa.Column('state', sa.String(length=100), nullable=False,
                comment='État/Région'),
        sa.Column('postal_code', sa.String(length=20), nullable=False,
                comment='Code postal'),
        sa.Column('country', sa.String(length=100), nullable=False,
                comment='Pays'),
        sa.Column('is_billing', sa.Boolean(), nullable=False,
                comment="Indique si c'est une adresse de facturation"),
        sa.Column('is_shipping', sa.Boolean(), nullable=False,
                comment="Indique si c'est une adresse de livraison"),
        sa.Column('is_active', sa.Boolean(), nullable=False,
                comment="Indique si l'adresse est active ou supprimée"),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                comment="Date de création de l'adresse"),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                comment='Date de dernière mise à jour'),
        sa.ForeignKeyConstraint(['customer_id'], [CUSTOMER_PK], ),
        sa.PrimaryKeyConstraint('id'),
        schema='app_schema'
    )
    op.create_table('customer_mails',   # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment='Identifiant mail unique'),
        sa.Column('customer_id', sa.Integer(), nullable=False,
                  comment='Id client associé à ce mail'),
        sa.Column('email_name', sa.String(length=100), nullable=True,
                  comment="Nom de l'e-mail (ex: perso, pro)"),
        sa.Column('email', sa.String(length=150), nullable=False,
                  comment='Adresse e-mail du client'),
        sa.Column('is_active', sa.Boolean(), nullable=False,
                  comment="Indique si l'e-mail est actif ou supprimé"),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment="Date de création de l'e-mail"),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment="Date de dernière mise à jour de l'e-mail"),
        sa.ForeignKeyConstraint(['customer_id'], [CUSTOMER_PK], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        schema='app_schema'
    )
    op.create_table('customer_parts',   # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                comment='Identifiant Part unique'),
        sa.Column('customer_id', sa.Integer(), nullable=False,
                comment='Id client associé à part'),
        sa.Column('first_name', sa.String(length=100), nullable=False),
        sa.Column('last_name', sa.String(length=100), nullable=False),
        sa.Column('date_of_birth', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], [CUSTOMER_PK], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('customer_id'),
        schema='app_schema'
    )
    op.create_table('customer_phones',  # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment='Identifiant téléphone unique'),
        sa.Column('customer_id', sa.Integer(), nullable=False,
                  comment='Id client associé à ce téléphone'),
        sa.Column('phone_name', sa.String(length=100), nullable=True,
                  comment='Nom du téléphone (ex: mobile, fixe)'),
        sa.Column('phone_number', sa.String(length=20), nullable=False,
                  comment='Numéro de téléphone du client'),
        sa.Column('is_active', sa.Boolean(), nullable=False,
                  comment='Indique si le téléphone est actif ou supprimé'),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment='Date de création du téléphone'),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment='Date de dernière MàJ du téléphone'),
        sa.ForeignKeyConstraint(['customer_id'], [CUSTOMER_PK], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('phone_number'),
        schema='app_schema'
    )
    op.create_table('customer_pros',    # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                comment='Identifiant unique'),
        sa.Column('customer_id', sa.Integer(), nullable=False,
                comment='Identifiant du client associé'),
        sa.Column('company_name', sa.String(length=200), nullable=False,
                comment="Nom de l'entreprise"),
        sa.Column('siret_number', sa.String(length=14), nullable=False,
                comment="Numéro SIRET de l'entreprise"),
        sa.Column('vat_number', sa.String(length=50), nullable=True,
                comment='Numéro de TVA intracommunautaire'),
        sa.ForeignKeyConstraint(['customer_id'], [CUSTOMER_PK], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('customer_id'),
        sa.UniqueConstraint('siret_number'),
        sa.UniqueConstraint('vat_number'),
        schema='app_schema'
    )
    op.create_table('customer_sync_logs',   # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('sync_source', sa.String(length=50), nullable=False),
        sa.Column('sync_direction', sa.String(length=20), nullable=False),
        sa.Column('sync_status', sa.String(length=20), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=True),
        sa.Column('external_system', sa.String(length=50), nullable=False),
        sa.Column('fields_synced', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('synced_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['app_schema.customers.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='app_schema'
    )
    op.create_table('general_objects',  # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment="Identifiant unique de l'objet"),
        sa.Column('supplier_id', sa.Integer(), nullable=False,
                  comment="Identifiant du fournisseur de l'objet"),
        sa.Column('general_object_type', sa.String(), nullable=False,
                  comment="Type d'objet"),
        sa.Column('ean13', sa.String(), nullable=False,
                  comment="Code EAN13 de l'objet"),
        sa.Column('name', sa.String(), nullable=False, comment="Nom de l'objet"),
        sa.Column('description', sa.String(), nullable=False,
                  comment="Description de l'objet"),
        sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False,
                  comment="Prix de l'objet"),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment="Date de création de l'objet"),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment="Date de dernière mise à jour de l'objet"),
        sa.Column('last_inventory_timestamp', sa.DateTime(), nullable=False,
                  comment='Dernier inventaire'),
        sa.Column('is_active', sa.Boolean(), nullable=False,
                  comment="Indique si l'objet est actif pour la vente"),
        sa.ForeignKeyConstraint(['supplier_id'], ['app_schema.suppliers.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='app_schema'
    )
    op.create_table('books',    # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment='Identifiant unique du livre'),
        sa.Column('general_object_id', sa.Integer(), nullable=False,
                  comment='Identifiant objet associé'),
        sa.Column('author', sa.String(), nullable=False, comment='Auteur du livre'),
        sa.Column('publisher', sa.String(), nullable=False, comment='Éditeur du livre'),
        sa.Column('diffuser', sa.String(), nullable=False, comment='Diffuseur du livre'),
        sa.Column('editor', sa.String(), nullable=False, comment='Éditeur du livre'),
        sa.Column('genre', sa.String(), nullable=False, comment='Genre du livre'),
        sa.Column('publication_year', sa.Integer(), nullable=False,
                  comment='Année de publication du livre'),
        sa.Column('pages', sa.Integer(), nullable=False, comment='Nombre de pages du livre'),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment='Date de création du livre'),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment='Date de dernière mise à jour du livre'),
        sa.ForeignKeyConstraint(['general_object_id'], [GENERAL_OBJECT_PK], ),
        sa.PrimaryKeyConstraint('id'),
        schema='app_schema'
    )
    op.create_table('inventory_movements',  # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('general_object_id', sa.Integer(), nullable=False,
                  comment="ID de l'objet"),
        sa.Column('movement_type', sa.String(), nullable=False,
                  comment='Type de mouvement (in/out/reserved/inventory)'),
        sa.Column('quantity', sa.Integer(), nullable=False,
                  comment='Quantité du mouvement'),
        sa.Column('movement_timestamp', sa.DateTime(), nullable=False,
                  comment='Date et heure du mouvement'),
        sa.Column('price_at_movement', sa.Float(), nullable=False,
                  comment="Prix d'objet au moment du mouvement"),
        sa.Column('source', sa.String(), nullable=False,
                  comment='Source du mouvement'),
        sa.Column('destination', sa.String(), nullable=False,
                  comment='Destination du mouvement'),
        sa.Column('notes', sa.String(), nullable=False,
                  comment='Notes supplémentaires sur le mouvement'),
        sa.ForeignKeyConstraint(['general_object_id'], [GENERAL_OBJECT_PK], ),
        sa.PrimaryKeyConstraint('id'),
        schema='app_schema'
    )
    op.create_table('media_files',  # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment='Identifiant unique du fichier média'),
        sa.Column('general_object_id', sa.Integer(), nullable=False,
                  comment='Identifiant de la métadonnée associée'),
        sa.Column('file_name', sa.String(), nullable=False,
                  comment='Nom du fichier média'),
        sa.Column('file_type', sa.String(), nullable=False,
                  comment='Type du fichier média (ex: image/jpeg)'),
        sa.Column('alt_text', sa.String(), nullable=False,
                  comment='Texte alternatif pour le fichier média'),
        sa.Column('file_data', sa.LargeBinary(), nullable=True,
                  comment='Données brutes du fichier média'),
        sa.Column('file_link', sa.String(), nullable=True,
                  comment='Lien vers le fichier média ext.'),
        sa.Column('uploaded_at', sa.DateTime(), nullable=False,
                  comment='Date de téléchargement du fichier média'),
        sa.Column('is_principal', sa.Boolean(), nullable=False,
                  comment="Indique si c'est l'image principale"),
        sa.ForeignKeyConstraint(['general_object_id'], [GENERAL_OBJECT_PK], ),
        sa.PrimaryKeyConstraint('id'),
        schema='app_schema'
    )
    op.create_table('obj_metadatas',    # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment='Identifiant unique de la métadonnée'),
        sa.Column('general_object_id', sa.Integer(), nullable=False,
                  comment="Identifiant de l'objet général associé"),
        sa.Column('semistructured_data', sa.JSON(), nullable=False,
                  comment='Données au format JSON'),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment='Date de création de la métadonnée'),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment='Date de dernière MàJ de la métadonnée'),
        sa.ForeignKeyConstraint(['general_object_id'], [GENERAL_OBJECT_PK], ),
        sa.PrimaryKeyConstraint('id'),
        schema='app_schema'
    )
    op.create_table('object_tags',  # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment="Identifiant unique de l'association objet-tag"),
        sa.Column('general_object_id', sa.Integer(), nullable=False,
                  comment="Identifiant de l'objet général associé"),
        sa.Column('tag_id', sa.Integer(), nullable=False,
                  comment='Identifiant du tag associé'),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment="Date de création de l'association"),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment="Date de dernière MàJ de l'association"),
        sa.ForeignKeyConstraint(['general_object_id'], [GENERAL_OBJECT_PK], ),
        sa.ForeignKeyConstraint(['tag_id'], ['app_schema.tags.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='app_schema'
    )
    op.create_table('orders',   # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('reference', sa.String(length=14), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('invoice_address_id', sa.Integer(), nullable=False,
                comment='Adresse de facturat°'),
        sa.Column('delivery_address_id', sa.Integer(), nullable=False,
                comment='Adresse de livraison'),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('create_source', sa.String(length=50), nullable=False,
                comment='Source de la commande'),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                comment='Date de création de la commande'),
        sa.Column('update_source', sa.String(length=50), nullable=True,
                comment=SOURCE_SYNC),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                comment='Date dernière mise à jour de la commande'),
        sa.Column('last_synced_at', sa.DateTime(), nullable=True,
                comment=LAST_SYNC),
        sa.ForeignKeyConstraint(['customer_id'], [CUSTOMER_PK], ),
        sa.ForeignKeyConstraint(['delivery_address_id'], [CUSTOMER_ADDRESS_PK], ),
        sa.ForeignKeyConstraint(['invoice_address_id'], [CUSTOMER_ADDRESS_PK], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('reference'),
        schema='app_schema'
    )
    op.create_table('other_objects',    # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment="Identifiant unique de l'autre objet"),
        sa.Column('general_object_id', sa.Integer(), nullable=False,
                  comment="Id de l'objet général associé"),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment="Date de création de l'objet autre"),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment="Date de dernière MàJ de l'objet autre"),
        sa.ForeignKeyConstraint(['general_object_id'], [GENERAL_OBJECT_PK], ),
        sa.PrimaryKeyConstraint('id'),
        schema='app_schema'
    )
    op.create_table('order_lines',  # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment='Identifiant unique de la ligne de commande'),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('invoice_id', sa.Integer(), nullable=True,
                  comment='Facture associée à la ligne de commande'),
        sa.Column('shipment_id', sa.Integer(), nullable=True,
                  comment='Envoi associé à la ligne de commande'),
        sa.Column('general_object_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False, comment='Quantité commandée'),
        sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False,
                  comment="Prix unitaire en centimes d'euro"),
        sa.Column('vat_rate', sa.Numeric(precision=10, scale=3), nullable=False,
                  comment='Taux de TVA en pourcentage'),
        sa.Column('create_source', sa.String(length=50), nullable=False,
                  comment='Source de la ligne de commande'),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment='Date de création de la ligne de commande'),
        sa.Column('update_source', sa.String(length=50), nullable=True,
                  comment='Source last MaJ de la ligne de commande'),
        sa.Column('updated_at', sa.DateTime(), nullable=True,
                  comment='Date last MaJ de la ligne de commande'),
        sa.ForeignKeyConstraint(['general_object_id'], [GENERAL_OBJECT_PK], ),
        sa.ForeignKeyConstraint(['invoice_id'], [INVOICE_PK], ),
        sa.ForeignKeyConstraint(['order_id'], [ORDER_PK], ),
        sa.ForeignKeyConstraint(['shipment_id'], [SHIPMENT_PK], ),
        sa.PrimaryKeyConstraint('id'),
        schema='app_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_lines', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('other_objects', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('orders', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('object_tags', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('obj_metadatas', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('media_files', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('inventory_movements', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('books', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('general_objects', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('customer_sync_logs', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('customer_pros', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('customer_phones', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('customer_parts', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('customer_mails', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('customer_addresses', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('tags', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('suppliers', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('shipments', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('invoices', schema='app_schema')   # pylint: disable=no-member
    op.drop_table('customers', schema='app_schema')   # pylint: disable=no-member
    # ### end Alembic commands ###
