"""first_migration

Revision ID: 3312b31d6cf2
Revises: 
Create Date: 2026-04-22 05:37:48.174252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3312b31d6cf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique du client'),
    sa.Column('wpwc_id', sa.String(length=50), nullable=True, comment='Identifiant WooCommerce'),
    sa.Column('henrri_id', sa.String(length=100), nullable=True, comment='Identifiant Henrri'),
    sa.Column('customer_type', sa.String(length=20), nullable=False, comment='Type de client : part/pro'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Statut actif/inactif du client'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création du client'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière mise à jour du client'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='Dernière synchronisation'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('henrri_id'),
    sa.UniqueConstraint('wpwc_id'),
    schema='app_schema'
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique du fournisseur'),
    sa.Column('name', sa.String(), nullable=False, comment='Nom du fournisseur'),
    sa.Column('gln13', sa.String(), nullable=False, comment='Code GLN du fournisseur'),
    sa.Column('siren_siret', sa.String(), nullable=True, comment='Numéro SIREN ou SIRET du fournisseur'),
    sa.Column('vat_number', sa.String(), nullable=True, comment='Numéro de TVA intracom fournisseur'),
    sa.Column('address', sa.String(), nullable=True, comment='Adresse complète du fournisseur'),
    sa.Column('contact_email', sa.String(), nullable=True, comment='Email de contact du fournisseur'),
    sa.Column('contact_phone', sa.String(), nullable=True, comment='Téléphone de contact du fournisseur'),
    sa.Column('contact_fax', sa.String(), nullable=True, comment='Fax de contact du fournisseur'),
    sa.Column('web_site', sa.String(), nullable=True, comment='Site web du fournisseur'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indique si le fournisseur est actif'),
    sa.Column('edi_active', sa.Boolean(), nullable=False, comment="Indique si le fournisseur est actif pour l'EDI"),
    sa.Column('collect_days', sa.String(), nullable=True, comment="Jours de collecte des commandes (ex: '12345' pour LMMJV)"),
    sa.Column('cutoff_time', sa.String(), nullable=True, comment='Heure limite de PEC des commandes pour le jour même.'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création du fournisseur'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière MàJ du fournisseur'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gln13'),
    schema='app_schema'
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique du tag'),
    sa.Column('name', sa.String(), nullable=False, comment='Nom du tag'),
    sa.Column('description', sa.String(), nullable=False, comment='Description du tag'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création du tag'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière MàJ du tag'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='app_schema'
    )
    op.create_table('vat_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique du taux de TVA'),
    sa.Column('code', sa.Integer(), nullable=False, comment='Code TVA (0=super-réduit, 1=réduit, 2=intermédiaire, 3=normal)'),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Taux de TVA en pourcentage (ex: 5.50)'),
    sa.Column('label', sa.String(), nullable=False, comment='Libellé du taux (ex: Taux réduit)'),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False, comment='Date de début de validité du taux'),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True, comment='Date de fin de validité (NULL = taux actuellement en vigueur)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'date_start', name='uq_vat_rates_code_date_start'),
    schema='app_schema'
    )
    op.create_table('customer_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='Identifiant du client associé'),
    sa.Column('address_name', sa.String(length=100), nullable=True, comment="Nom d'adresse (ex: home, work)"),
    sa.Column('address_line1', sa.String(length=200), nullable=False, comment="Ligne d'adresse 1"),
    sa.Column('address_line2', sa.String(length=200), nullable=True, comment="Ligne d'adresse 2"),
    sa.Column('city', sa.String(length=100), nullable=False, comment='Ville'),
    sa.Column('state', sa.String(length=100), nullable=False, comment='État/Région'),
    sa.Column('postal_code', sa.String(length=20), nullable=False, comment='Code postal'),
    sa.Column('country', sa.String(length=100), nullable=False, comment='Pays'),
    sa.Column('is_billing', sa.Boolean(), nullable=False, comment="Indique si c'est une adresse de facturation"),
    sa.Column('is_shipping', sa.Boolean(), nullable=False, comment="Indique si c'est une adresse de livraison"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment="Indique si l'adresse est active ou supprimée"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'adresse"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière mise à jour'),
    sa.ForeignKeyConstraint(['customer_id'], ['app_schema.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('customer_mails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant email unique'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='Id client associé à cet email'),
    sa.Column('email_name', sa.String(length=100), nullable=True, comment="Nom de l'e-mail (ex: perso, pro)"),
    sa.Column('email', sa.String(length=150), nullable=False, comment='Adresse e-mail du client'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment="Indique si l'e-mail est actif ou supprimé"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'e-mail"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment="Date de dernière mise à jour de l'e-mail"),
    sa.ForeignKeyConstraint(['customer_id'], ['app_schema.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='app_schema'
    )
    op.create_table('customer_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant Part unique'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='Id client associé à part'),
    sa.Column('civil_title', sa.String(length=20), nullable=True, comment='Civilité (ex: M., Mme, Dr)'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['app_schema.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id'),
    schema='app_schema'
    )
    op.create_table('customer_phones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant téléphone unique'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='Id client associé à ce téléphone'),
    sa.Column('phone_name', sa.String(length=100), nullable=True, comment='Nom du téléphone (ex: mobile, fixe)'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='Numéro de téléphone du client'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indique si le téléphone est actif ou supprimé'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création du téléphone'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière MàJ du téléphone'),
    sa.ForeignKeyConstraint(['customer_id'], ['app_schema.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    schema='app_schema'
    )
    op.create_table('customer_pros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='Identifiant du client associé'),
    sa.Column('company_name', sa.String(length=200), nullable=False, comment="Nom de l'entreprise"),
    sa.Column('siret_number', sa.String(length=14), nullable=False, comment="Numéro SIRET de l'entreprise"),
    sa.Column('vat_number', sa.String(length=50), nullable=True, comment='Numéro de TVA intracommunautaire'),
    sa.ForeignKeyConstraint(['customer_id'], ['app_schema.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id'),
    sa.UniqueConstraint('siret_number'),
    sa.UniqueConstraint('vat_number'),
    schema='app_schema'
    )
    op.create_table('customer_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sync_source', sa.String(length=50), nullable=False),
    sa.Column('sync_direction', sa.String(length=20), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('external_system', sa.String(length=50), nullable=False),
    sa.Column('fields_synced', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['app_schema.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('general_objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment="Identifiant unique de l'objet"),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment="Identifiant du fournisseur de l'objet"),
    sa.Column('general_object_type', sa.String(), nullable=False, comment="Type d'objet"),
    sa.Column('ean13', sa.String(), nullable=False, comment="Code EAN13 de l'objet"),
    sa.Column('name', sa.String(), nullable=False, comment="Nom de l'objet"),
    sa.Column('description', sa.String(), nullable=False, comment="Description de l'objet"),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment="Prix de l'objet"),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True, comment="Prix d'achat de l'objet"),
    sa.Column('vat_rate_id', sa.Integer(), nullable=True, comment="Code TVA associé à l'objet (référence la table vat_rates)"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'objet"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment="Date de dernière mise à jour de l'objet"),
    sa.Column('last_inventory_timestamp', sa.DateTime(), nullable=False, comment='Dernier inventaire'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment="Indique si l'objet est actif pour la vente"),
    sa.ForeignKeyConstraint(['supplier_id'], ['app_schema.suppliers.id'], ),
    sa.ForeignKeyConstraint(['vat_rate_id'], ['app_schema.vat_rates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean13'),
    schema='app_schema'
    )
    op.create_table('order_in',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_ref', sa.String(), nullable=False, comment='Numéro de commande'),
    sa.Column('external_ref', sa.String(), nullable=True, comment='Ref externe'),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='ID du fournisseur de la commande'),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False, comment='Valeur totale de la commande'),
    sa.Column('order_state', sa.String(), nullable=False, comment='État de la commande'),
    sa.ForeignKeyConstraint(['supplier_id'], ['app_schema.suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique du livre'),
    sa.Column('general_object_id', sa.Integer(), nullable=False, comment='Identifiant objet associé'),
    sa.Column('author', sa.String(), nullable=False, comment='Auteur du livre'),
    sa.Column('diffuser', sa.String(), nullable=False, comment='Diffuseur du livre'),
    sa.Column('editor', sa.String(), nullable=False, comment='Éditeur du livre'),
    sa.Column('genre', sa.String(), nullable=False, comment='Genre du livre'),
    sa.Column('publication_year', sa.Integer(), nullable=False, comment='Année de publication du livre'),
    sa.Column('pages', sa.Integer(), nullable=False, comment='Nombre de pages du livre'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création du livre'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière mise à jour du livre'),
    sa.ForeignKeyConstraint(['general_object_id'], ['app_schema.general_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('dilicom_referential',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ean13', sa.String(), nullable=False, comment="EAN13 de l'objet"),
    sa.Column('gln13', sa.String(), nullable=False, comment='GLN13 du fournisseur'),
    sa.Column('create_ref', sa.Boolean(), nullable=False, comment="Indique si l'objet doit être créé"),
    sa.Column('delete_ref', sa.Boolean(), nullable=False, comment="Indique si l'objet doit être supprimé"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indique si la référence est active'),
    sa.Column('dilicom_synced', sa.Boolean(), nullable=False, comment='Synchronisé avec Dilicom ou non'),
    sa.Column('created_at', sa.String(), nullable=False, comment='Date de création de la référence'),
    sa.Column('updated_at', sa.String(), nullable=False, comment='Date de dernière MàJ de la référence'),
    sa.ForeignKeyConstraint(['ean13'], ['app_schema.general_objects.ean13'], ),
    sa.ForeignKeyConstraint(['gln13'], ['app_schema.suppliers.gln13'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('general_object_id', sa.Integer(), nullable=False, comment="ID de l'objet"),
    sa.Column('movement_type', sa.String(), nullable=False, comment='Type de mouvement (in/out/reserved/inventory/pending)'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Quantité du mouvement'),
    sa.Column('movement_timestamp', sa.DateTime(), nullable=False, comment='Date et heure du mouvement'),
    sa.Column('price_at_movement', sa.Float(), nullable=False, comment="Prix d'objet au moment du mouvement"),
    sa.Column('source', sa.String(), nullable=False, comment='Source du mouvement'),
    sa.Column('destination', sa.String(), nullable=False, comment='Destination du mouvement'),
    sa.Column('notes', sa.String(), nullable=False, comment='Notes supplémentaires sur le mouvement'),
    sa.ForeignKeyConstraint(['general_object_id'], ['app_schema.general_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique du fichier média'),
    sa.Column('general_object_id', sa.Integer(), nullable=False, comment='Identifiant de la métadonnée associée'),
    sa.Column('file_name', sa.String(), nullable=False, comment='Nom du fichier média'),
    sa.Column('file_type', sa.String(), nullable=False, comment='Type du fichier média (ex: image/jpeg)'),
    sa.Column('alt_text', sa.String(), nullable=True, comment='Texte alternatif pour le fichier média'),
    sa.Column('file_data', sa.LargeBinary(), nullable=True, comment='Données brutes du fichier média'),
    sa.Column('file_link', sa.String(), nullable=True, comment='Lien vers le fichier média ext.'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False, comment='Date de téléchargement du fichier média'),
    sa.Column('is_principal', sa.Boolean(), nullable=False, comment="Indique si c'est l'image principale"),
    sa.ForeignKeyConstraint(['general_object_id'], ['app_schema.general_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('obj_metadatas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique de la métadonnée'),
    sa.Column('general_object_id', sa.Integer(), nullable=False, comment="Identifiant de l'objet général associé"),
    sa.Column('semistructured_data', sa.JSON(), nullable=False, comment='Données au format JSON'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création de la métadonnée'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière MàJ de la métadonnée'),
    sa.ForeignKeyConstraint(['general_object_id'], ['app_schema.general_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('object_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment="Identifiant unique de l'association objet-tag"),
    sa.Column('general_object_id', sa.Integer(), nullable=False, comment="Identifiant de l'objet général associé"),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='Identifiant du tag associé'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'association"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment="Date de dernière MàJ de l'association"),
    sa.ForeignKeyConstraint(['general_object_id'], ['app_schema.general_objects.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['app_schema.tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=14), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_address_id', sa.Integer(), nullable=True, comment='Adresse de facturat°'),
    sa.Column('delivery_address_id', sa.Integer(), nullable=True, comment='Adresse de livraison'),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('create_source', sa.String(length=50), nullable=False, comment='Source de la commande'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création de la commande'),
    sa.Column('update_source', sa.String(length=50), nullable=True, comment='Source de la dernière mise à jour'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date dernière mise à jour de la commande'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='Dernière synchronisation'),
    sa.ForeignKeyConstraint(['customer_id'], ['app_schema.customers.id'], ),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['app_schema.customer_addresses.id'], ),
    sa.ForeignKeyConstraint(['invoice_address_id'], ['app_schema.customer_addresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference'),
    schema='app_schema'
    )
    op.create_table('other_objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment="Identifiant unique de l'autre objet"),
    sa.Column('general_object_id', sa.Integer(), nullable=False, comment="Id de l'objet général associé"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'objet autre"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment="Date de dernière MàJ de l'objet autre"),
    sa.ForeignKeyConstraint(['general_object_id'], ['app_schema.general_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Commande parente'),
    sa.Column('ext_id', sa.String(length=50), nullable=True, comment='ID externe de la facture (Henrri)'),
    sa.Column('reference', sa.String(length=14), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Montant total de la facture'),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Montant de la TVA de la facture'),
    sa.Column('create_source', sa.String(length=50), nullable=False, comment='Source de la facture'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création de la facture'),
    sa.Column('update_source', sa.String(length=50), nullable=True, comment='Source de la dernière mise à jour'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Date dernière mise à jour de la facture'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='Dernière synchronisation'),
    sa.ForeignKeyConstraint(['order_id'], ['app_schema.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference'),
    schema='app_schema'
    )
    op.create_table('order_in_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_in_id', sa.Integer(), nullable=False, comment="ID de la commande d'entrée"),
    sa.Column('general_object_id', sa.Integer(), nullable=False, comment="ID de l'objet"),
    sa.Column('inventory_movement_id', sa.Integer(), nullable=True, comment='ID du mouvement de stock associé'),
    sa.Column('qty_ordered', sa.Integer(), nullable=False, comment='Quantité commandée'),
    sa.Column('qty_received', sa.Integer(), nullable=False, comment='Quantité reçue'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2, decimal_return_scale=True), nullable=False, comment="Prix unitaire en centimes d'euro"),
    sa.Column('vat_rate', sa.Numeric(precision=10, scale=3, decimal_return_scale=True), nullable=False, comment='Taux de TVA en pourcentage'),
    sa.Column('line_state', sa.String(), nullable=False, comment='État de la ligne de commande'),
    sa.ForeignKeyConstraint(['general_object_id'], ['app_schema.general_objects.id'], ),
    sa.ForeignKeyConstraint(['inventory_movement_id'], ['app_schema.inventory_movements.id'], ),
    sa.ForeignKeyConstraint(['order_in_id'], ['app_schema.order_in.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique de la ligne de commande'),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('general_object_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Quantité commandée'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='État de la ligne'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Prix unitaire HT en euros'),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=False, comment='Remise en pourcentage'),
    sa.Column('vat_rate', sa.Numeric(precision=10, scale=3), nullable=False, comment='Taux de TVA en pourcentage'),
    sa.Column('create_source', sa.String(length=50), nullable=False, comment='Source de la ligne de commande'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création de la ligne de commande'),
    sa.Column('update_source', sa.String(length=50), nullable=True, comment='Source last MaJ de la ligne de commande'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Date last MaJ de la ligne de commande'),
    sa.ForeignKeyConstraint(['general_object_id'], ['app_schema.general_objects.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['app_schema.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Commande parente'),
    sa.Column('reference', sa.String(length=14), nullable=False),
    sa.Column('carrier', sa.String(length=50), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=True),
    sa.Column('create_source', sa.String(length=50), nullable=False, comment="Source de l'envoi"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'envoi"),
    sa.Column('update_source', sa.String(length=50), nullable=True, comment='Source de la dernière mise à jour'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment="Date dernière mise à jour de l'envoi"),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='Dernière synchronisation'),
    sa.ForeignKeyConstraint(['order_id'], ['app_schema.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference'),
    schema='app_schema'
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=14), nullable=False, comment='Référence de la ligne de facture'),
    sa.Column('description', sa.String(length=255), nullable=False, comment='Description de la ligne de facture'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Quantité facturée'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Prix unitaire de la ligne de facture'),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=False, comment='Remise appliquée à la ligne de facture'),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Taux de TVA appliqué à la ligne de facture'),
    sa.ForeignKeyConstraint(['invoice_id'], ['app_schema.invoices.id'], ),
    sa.ForeignKeyConstraint(['order_line_id'], ['app_schema.order_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('shipment_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Quantité expédiée'),
    sa.ForeignKeyConstraint(['order_line_id'], ['app_schema.order_lines.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['app_schema.shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_lines', schema='app_schema')
    op.drop_table('invoice_lines', schema='app_schema')
    op.drop_table('shipments', schema='app_schema')
    op.drop_table('order_lines', schema='app_schema')
    op.drop_table('order_in_lines', schema='app_schema')
    op.drop_table('invoices', schema='app_schema')
    op.drop_table('other_objects', schema='app_schema')
    op.drop_table('orders', schema='app_schema')
    op.drop_table('object_tags', schema='app_schema')
    op.drop_table('obj_metadatas', schema='app_schema')
    op.drop_table('media_files', schema='app_schema')
    op.drop_table('inventory_movements', schema='app_schema')
    op.drop_table('dilicom_referential', schema='app_schema')
    op.drop_table('books', schema='app_schema')
    op.drop_table('order_in', schema='app_schema')
    op.drop_table('general_objects', schema='app_schema')
    op.drop_table('customer_sync_logs', schema='app_schema')
    op.drop_table('customer_pros', schema='app_schema')
    op.drop_table('customer_phones', schema='app_schema')
    op.drop_table('customer_parts', schema='app_schema')
    op.drop_table('customer_mails', schema='app_schema')
    op.drop_table('customer_addresses', schema='app_schema')
    op.drop_table('vat_rates', schema='app_schema')
    op.drop_table('tags', schema='app_schema')
    op.drop_table('suppliers', schema='app_schema')
    op.drop_table('customers', schema='app_schema')
    # ### end Alembic commands ###
