"""Ajout de TVA par code

Revision ID: 60273a5078ce
Revises: 4cbce21d5738
Create Date: 2026-03-28 08:54:30.875139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60273a5078ce'
down_revision: Union[str, Sequence[str], None] = '4cbce21d5738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vat_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique du taux de TVA'),
    sa.Column('code', sa.Integer(), nullable=False, comment='Code TVA (0=super-réduit, 1=réduit, 2=intermédiaire, 3=normal)'),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Taux de TVA en pourcentage (ex: 5.50)'),
    sa.Column('label', sa.String(), nullable=False, comment='Libellé du taux (ex: Taux réduit)'),
    sa.Column('date_start', sa.DateTime(), nullable=False, comment='Date de début de validité du taux'),
    sa.Column('date_end', sa.DateTime(), nullable=True, comment='Date de fin de validité (NULL = taux actuellement en vigueur)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'date_start', name='uq_vat_rates_code_date_start'),
    schema='app_schema'
    )
    op.drop_constraint(op.f('books_general_object_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_addresses_customer_id_fkey'), 'customer_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'customer_addresses', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_mails_customer_id_fkey'), 'customer_mails', type_='foreignkey')
    op.create_foreign_key(None, 'customer_mails', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_parts_customer_id_fkey'), 'customer_parts', type_='foreignkey')
    op.create_foreign_key(None, 'customer_parts', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_phones_customer_id_fkey'), 'customer_phones', type_='foreignkey')
    op.create_foreign_key(None, 'customer_phones', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_pros_customer_id_fkey'), 'customer_pros', type_='foreignkey')
    op.create_foreign_key(None, 'customer_pros', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_sync_logs_customer_id_fkey'), 'customer_sync_logs', type_='foreignkey')
    op.create_foreign_key(None, 'customer_sync_logs', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('dilicom_referential_gln13_fkey'), 'dilicom_referential', type_='foreignkey')
    op.drop_constraint(op.f('dilicom_referential_ean13_fkey'), 'dilicom_referential', type_='foreignkey')
    op.create_foreign_key(None, 'dilicom_referential', 'suppliers', ['gln13'], ['gln13'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'dilicom_referential', 'general_objects', ['ean13'], ['ean13'], source_schema='app_schema', referent_schema='app_schema')
    op.add_column('general_objects', sa.Column('vat_rate_id', sa.Integer(), nullable=True, comment="Code TVA associé à l'objet (référence la table vat_rates)"))
    op.drop_constraint(op.f('general_objects_supplier_id_fkey'), 'general_objects', type_='foreignkey')
    op.create_foreign_key(None, 'general_objects', 'vat_rates', ['vat_rate_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'general_objects', 'suppliers', ['supplier_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('inventory_movements_general_object_id_fkey'), 'inventory_movements', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_movements', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('media_files_general_object_id_fkey'), 'media_files', type_='foreignkey')
    op.create_foreign_key(None, 'media_files', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('obj_metadatas_general_object_id_fkey'), 'obj_metadatas', type_='foreignkey')
    op.create_foreign_key(None, 'obj_metadatas', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('object_tags_tag_id_fkey'), 'object_tags', type_='foreignkey')
    op.drop_constraint(op.f('object_tags_general_object_id_fkey'), 'object_tags', type_='foreignkey')
    op.create_foreign_key(None, 'object_tags', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'object_tags', 'tags', ['tag_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('order_in_supplier_id_fkey'), 'order_in', type_='foreignkey')
    op.create_foreign_key(None, 'order_in', 'suppliers', ['supplier_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('order_in_lines_general_object_id_fkey'), 'order_in_lines', type_='foreignkey')
    op.drop_constraint(op.f('order_in_lines_order_in_id_fkey'), 'order_in_lines', type_='foreignkey')
    op.drop_constraint(op.f('order_in_lines_inventory_movement_id_fkey'), 'order_in_lines', type_='foreignkey')
    op.create_foreign_key(None, 'order_in_lines', 'order_in', ['order_in_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'order_in_lines', 'inventory_movements', ['inventory_movement_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'order_in_lines', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('order_lines_order_id_fkey'), 'order_lines', type_='foreignkey')
    op.drop_constraint(op.f('order_lines_shipment_id_fkey'), 'order_lines', type_='foreignkey')
    op.drop_constraint(op.f('order_lines_invoice_id_fkey'), 'order_lines', type_='foreignkey')
    op.drop_constraint(op.f('order_lines_general_object_id_fkey'), 'order_lines', type_='foreignkey')
    op.create_foreign_key(None, 'order_lines', 'shipments', ['shipment_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'order_lines', 'orders', ['order_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'order_lines', 'invoices', ['invoice_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'order_lines', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('orders_customer_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_delivery_address_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_invoice_address_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'customer_addresses', ['invoice_address_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'orders', 'customer_addresses', ['delivery_address_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('other_objects_general_object_id_fkey'), 'other_objects', type_='foreignkey')
    op.create_foreign_key(None, 'other_objects', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'other_objects', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('other_objects_general_object_id_fkey'), 'other_objects', 'general_objects', ['general_object_id'], ['id'])
    op.drop_constraint(None, 'orders', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('orders_invoice_address_id_fkey'), 'orders', 'customer_addresses', ['invoice_address_id'], ['id'])
    op.create_foreign_key(op.f('orders_delivery_address_id_fkey'), 'orders', 'customer_addresses', ['delivery_address_id'], ['id'])
    op.create_foreign_key(op.f('orders_customer_id_fkey'), 'orders', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'order_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'order_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'order_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'order_lines', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('order_lines_general_object_id_fkey'), 'order_lines', 'general_objects', ['general_object_id'], ['id'])
    op.create_foreign_key(op.f('order_lines_invoice_id_fkey'), 'order_lines', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key(op.f('order_lines_shipment_id_fkey'), 'order_lines', 'shipments', ['shipment_id'], ['id'])
    op.create_foreign_key(op.f('order_lines_order_id_fkey'), 'order_lines', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_in_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'order_in_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'order_in_lines', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('order_in_lines_inventory_movement_id_fkey'), 'order_in_lines', 'inventory_movements', ['inventory_movement_id'], ['id'])
    op.create_foreign_key(op.f('order_in_lines_order_in_id_fkey'), 'order_in_lines', 'order_in', ['order_in_id'], ['id'])
    op.create_foreign_key(op.f('order_in_lines_general_object_id_fkey'), 'order_in_lines', 'general_objects', ['general_object_id'], ['id'])
    op.drop_constraint(None, 'order_in', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('order_in_supplier_id_fkey'), 'order_in', 'suppliers', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'object_tags', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'object_tags', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('object_tags_general_object_id_fkey'), 'object_tags', 'general_objects', ['general_object_id'], ['id'])
    op.create_foreign_key(op.f('object_tags_tag_id_fkey'), 'object_tags', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(None, 'obj_metadatas', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('obj_metadatas_general_object_id_fkey'), 'obj_metadatas', 'general_objects', ['general_object_id'], ['id'])
    op.drop_constraint(None, 'media_files', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('media_files_general_object_id_fkey'), 'media_files', 'general_objects', ['general_object_id'], ['id'])
    op.drop_constraint(None, 'inventory_movements', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_movements_general_object_id_fkey'), 'inventory_movements', 'general_objects', ['general_object_id'], ['id'])
    op.drop_constraint(None, 'general_objects', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'general_objects', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('general_objects_supplier_id_fkey'), 'general_objects', 'suppliers', ['supplier_id'], ['id'])
    op.drop_column('general_objects', 'vat_rate_id')
    op.drop_constraint(None, 'dilicom_referential', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'dilicom_referential', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('dilicom_referential_ean13_fkey'), 'dilicom_referential', 'general_objects', ['ean13'], ['ean13'])
    op.create_foreign_key(op.f('dilicom_referential_gln13_fkey'), 'dilicom_referential', 'suppliers', ['gln13'], ['gln13'])
    op.drop_constraint(None, 'customer_sync_logs', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_sync_logs_customer_id_fkey'), 'customer_sync_logs', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_pros', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_pros_customer_id_fkey'), 'customer_pros', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_phones', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_phones_customer_id_fkey'), 'customer_phones', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_parts', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_parts_customer_id_fkey'), 'customer_parts', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_mails', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_mails_customer_id_fkey'), 'customer_mails', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_addresses', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_addresses_customer_id_fkey'), 'customer_addresses', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'books', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('books_general_object_id_fkey'), 'books', 'general_objects', ['general_object_id'], ['id'])
    op.drop_table('vat_rates', schema='app_schema')
    # ### end Alembic commands ###
