"""external_invoice_ref

Revision ID: d5a8b9b68a7f
Revises: a1b2c3d4e5f6
Create Date: 2026-04-04 13:41:55.980327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a8b9b68a7f'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_general_object_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_addresses_customer_id_fkey'), 'customer_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'customer_addresses', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_mails_customer_id_fkey'), 'customer_mails', type_='foreignkey')
    op.create_foreign_key(None, 'customer_mails', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_parts_customer_id_fkey'), 'customer_parts', type_='foreignkey')
    op.create_foreign_key(None, 'customer_parts', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_phones_customer_id_fkey'), 'customer_phones', type_='foreignkey')
    op.create_foreign_key(None, 'customer_phones', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_pros_customer_id_fkey'), 'customer_pros', type_='foreignkey')
    op.create_foreign_key(None, 'customer_pros', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_sync_logs_customer_id_fkey'), 'customer_sync_logs', type_='foreignkey')
    op.create_foreign_key(None, 'customer_sync_logs', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('dilicom_referential_gln13_fkey'), 'dilicom_referential', type_='foreignkey')
    op.drop_constraint(op.f('dilicom_referential_ean13_fkey'), 'dilicom_referential', type_='foreignkey')
    op.create_foreign_key(None, 'dilicom_referential', 'general_objects', ['ean13'], ['ean13'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'dilicom_referential', 'suppliers', ['gln13'], ['gln13'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('general_objects_supplier_id_fkey'), 'general_objects', type_='foreignkey')
    op.drop_constraint(op.f('general_objects_vat_rate_id_fkey'), 'general_objects', type_='foreignkey')
    op.create_foreign_key(None, 'general_objects', 'vat_rates', ['vat_rate_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'general_objects', 'suppliers', ['supplier_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('inventory_movements_general_object_id_fkey'), 'inventory_movements', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_movements', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('invoice_lines_invoice_id_fkey'), 'invoice_lines', type_='foreignkey')
    op.drop_constraint(op.f('invoice_lines_order_line_id_fkey'), 'invoice_lines', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_lines', 'invoices', ['invoice_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'invoice_lines', 'order_lines', ['order_line_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.add_column('invoices', sa.Column('ext_id', sa.String(length=50), nullable=True, comment='ID externe de la facture (Henrri)'))
    op.alter_column('invoices', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Commande parente')
    op.drop_constraint(op.f('fk_invoices_order_id'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'orders', ['order_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('media_files_general_object_id_fkey'), 'media_files', type_='foreignkey')
    op.create_foreign_key(None, 'media_files', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('obj_metadatas_general_object_id_fkey'), 'obj_metadatas', type_='foreignkey')
    op.create_foreign_key(None, 'obj_metadatas', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('object_tags_tag_id_fkey'), 'object_tags', type_='foreignkey')
    op.drop_constraint(op.f('object_tags_general_object_id_fkey'), 'object_tags', type_='foreignkey')
    op.create_foreign_key(None, 'object_tags', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'object_tags', 'tags', ['tag_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('order_in_supplier_id_fkey'), 'order_in', type_='foreignkey')
    op.create_foreign_key(None, 'order_in', 'suppliers', ['supplier_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('order_in_lines_inventory_movement_id_fkey'), 'order_in_lines', type_='foreignkey')
    op.drop_constraint(op.f('order_in_lines_order_in_id_fkey'), 'order_in_lines', type_='foreignkey')
    op.drop_constraint(op.f('order_in_lines_general_object_id_fkey'), 'order_in_lines', type_='foreignkey')
    op.create_foreign_key(None, 'order_in_lines', 'inventory_movements', ['inventory_movement_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'order_in_lines', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'order_in_lines', 'order_in', ['order_in_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('order_lines_general_object_id_fkey'), 'order_lines', type_='foreignkey')
    op.drop_constraint(op.f('order_lines_order_id_fkey'), 'order_lines', type_='foreignkey')
    op.create_foreign_key(None, 'order_lines', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'order_lines', 'orders', ['order_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('orders_invoice_address_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_customer_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_delivery_address_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'customer_addresses', ['delivery_address_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'orders', 'customer_addresses', ['invoice_address_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('other_objects_general_object_id_fkey'), 'other_objects', type_='foreignkey')
    op.create_foreign_key(None, 'other_objects', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('shipment_lines_shipment_id_fkey'), 'shipment_lines', type_='foreignkey')
    op.drop_constraint(op.f('shipment_lines_order_line_id_fkey'), 'shipment_lines', type_='foreignkey')
    op.create_foreign_key(None, 'shipment_lines', 'shipments', ['shipment_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'shipment_lines', 'order_lines', ['order_line_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.alter_column('shipments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Commande parente')
    op.drop_constraint(op.f('fk_shipments_order_id'), 'shipments', type_='foreignkey')
    op.create_foreign_key(None, 'shipments', 'orders', ['order_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shipments_order_id'), 'shipments', 'orders', ['order_id'], ['id'])
    op.alter_column('shipments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Commande parente')
    op.drop_constraint(None, 'shipment_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'shipment_lines', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('shipment_lines_order_line_id_fkey'), 'shipment_lines', 'order_lines', ['order_line_id'], ['id'])
    op.create_foreign_key(op.f('shipment_lines_shipment_id_fkey'), 'shipment_lines', 'shipments', ['shipment_id'], ['id'])
    op.drop_constraint(None, 'other_objects', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('other_objects_general_object_id_fkey'), 'other_objects', 'general_objects', ['general_object_id'], ['id'])
    op.drop_constraint(None, 'orders', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('orders_delivery_address_id_fkey'), 'orders', 'customer_addresses', ['delivery_address_id'], ['id'])
    op.create_foreign_key(op.f('orders_customer_id_fkey'), 'orders', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('orders_invoice_address_id_fkey'), 'orders', 'customer_addresses', ['invoice_address_id'], ['id'])
    op.drop_constraint(None, 'order_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'order_lines', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('order_lines_order_id_fkey'), 'order_lines', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('order_lines_general_object_id_fkey'), 'order_lines', 'general_objects', ['general_object_id'], ['id'])
    op.drop_constraint(None, 'order_in_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'order_in_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'order_in_lines', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('order_in_lines_general_object_id_fkey'), 'order_in_lines', 'general_objects', ['general_object_id'], ['id'])
    op.create_foreign_key(op.f('order_in_lines_order_in_id_fkey'), 'order_in_lines', 'order_in', ['order_in_id'], ['id'])
    op.create_foreign_key(op.f('order_in_lines_inventory_movement_id_fkey'), 'order_in_lines', 'inventory_movements', ['inventory_movement_id'], ['id'])
    op.drop_constraint(None, 'order_in', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('order_in_supplier_id_fkey'), 'order_in', 'suppliers', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'object_tags', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'object_tags', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('object_tags_general_object_id_fkey'), 'object_tags', 'general_objects', ['general_object_id'], ['id'])
    op.create_foreign_key(op.f('object_tags_tag_id_fkey'), 'object_tags', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(None, 'obj_metadatas', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('obj_metadatas_general_object_id_fkey'), 'obj_metadatas', 'general_objects', ['general_object_id'], ['id'])
    op.drop_constraint(None, 'media_files', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('media_files_general_object_id_fkey'), 'media_files', 'general_objects', ['general_object_id'], ['id'])
    op.drop_constraint(None, 'invoices', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoices_order_id'), 'invoices', 'orders', ['order_id'], ['id'])
    op.alter_column('invoices', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Commande parente')
    op.drop_column('invoices', 'ext_id')
    op.drop_constraint(None, 'invoice_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'invoice_lines', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_lines_order_line_id_fkey'), 'invoice_lines', 'order_lines', ['order_line_id'], ['id'])
    op.create_foreign_key(op.f('invoice_lines_invoice_id_fkey'), 'invoice_lines', 'invoices', ['invoice_id'], ['id'])
    op.drop_constraint(None, 'inventory_movements', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_movements_general_object_id_fkey'), 'inventory_movements', 'general_objects', ['general_object_id'], ['id'])
    op.drop_constraint(None, 'general_objects', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'general_objects', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('general_objects_vat_rate_id_fkey'), 'general_objects', 'vat_rates', ['vat_rate_id'], ['id'])
    op.create_foreign_key(op.f('general_objects_supplier_id_fkey'), 'general_objects', 'suppliers', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'dilicom_referential', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'dilicom_referential', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('dilicom_referential_ean13_fkey'), 'dilicom_referential', 'general_objects', ['ean13'], ['ean13'])
    op.create_foreign_key(op.f('dilicom_referential_gln13_fkey'), 'dilicom_referential', 'suppliers', ['gln13'], ['gln13'])
    op.drop_constraint(None, 'customer_sync_logs', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_sync_logs_customer_id_fkey'), 'customer_sync_logs', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_pros', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_pros_customer_id_fkey'), 'customer_pros', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_phones', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_phones_customer_id_fkey'), 'customer_phones', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_parts', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_parts_customer_id_fkey'), 'customer_parts', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_mails', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_mails_customer_id_fkey'), 'customer_mails', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_addresses', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_addresses_customer_id_fkey'), 'customer_addresses', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'books', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('books_general_object_id_fkey'), 'books', 'general_objects', ['general_object_id'], ['id'])
    # ### end Alembic commands ###
