FROM docker.io/library/postgres:18-bookworm

# Installer envsubst (pour le script de génération)
RUN apt-get update && apt-get install -y gettext

# Définir les options d'initdb pour utiliser la locale française
ENV POSTGRES_INITDB_ARGS="--encoding=UTF8 --locale=fr_FR.utf8 --lc-collate=fr_FR.utf8 --lc-ctype=fr_FR.utf8"

# Créer le répertoire pour les scripts d'initialisation
WORKDIR /docker-entrypoint-initdb.d

# Copier les fichiers
COPY tests/init_postgres/00_generate_models.sh .
COPY tests/init_postgres/*.sql.pattern .
COPY tests/init_postgres/04_secure_hba.sh .
COPY tests/init_postgres/05_secure_conf.sh .
COPY tests/init_postgres/99_cleanup.sh .

RUN chmod +x 00_generate_models.sh 04_secure_hba.sh 05_secure_conf.sh 99_cleanup.sh \
    && chown -R postgres:postgres /docker-entrypoint-initdb.d

# Copier le fichier .env global dans un emplacement temporaire
COPY databases/main/.env.db_main /tmp/.env

# Exécuter le script de génération avant le démarrage
RUN chmod +x 00_generate_models.sh && \
    set -a && \
    . /tmp/.env && \
    set +a && \
    ./00_generate_models.sh && \
    chmod 644 *.sql && \
    rm 00_generate_models.sh *.pattern && \
    ls -la
