FROM python:3.14-slim

WORKDIR /app

# Installer les dépendances
COPY migrations/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Définir le point d'entrée pour Alembic
CMD ["alembic"]