# generated by datamodel-codegen:
#   filename:  customer_put.json
#   timestamp: 2026-05-12T16:46:22+00:00

from __future__ import annotations

from enum import Enum
from pydantic import BaseModel


class Billing(BaseModel):
    first_name: str | None = None
    last_name: str | None = None
    company: str | None = None
    address_1: str | None = None
    address_2: str | None = None
    city: str | None = None
    state: str | None = None
    postcode: str | None = None
    country: str | None = None
    email: str
    phone: str | None = None


class Shipping(BaseModel):
    first_name: str | None = None
    last_name: str | None = None
    company: str | None = None
    address_1: str | None = None
    address_2: str | None = None
    city: str | None = None
    state: str | None = None
    postcode: str | None = None
    country: str | None = None


class MetaDatum(BaseModel):
    id: int | None = None
    key: str
    value: str | CustomerType | None = None


class CustomerType(str, Enum):
    part = "Particulier"
    pro = "Professionnel"


class WooCustomerPut(BaseModel):
    email: str
    first_name: str | None = None
    last_name: str | None = None
    username: str | None = None
    billing: Billing | None = None
    shipping: Shipping | None = None
    meta_data: list[MetaDatum] | None = None

    def set_meta_type(self, value: str | CustomerType):
        if self.meta_data:
            for meta in self.meta_data:
                if meta.key == '_billing_wooccm10':
                    meta.value = value
                    return
        else:
            self.meta_data = []
        self.meta_data.append(MetaDatum(id=None, key='_billing_wooccm10', value=value))

    def set_meta_rs(self, value: str):
        if self.meta_data:
            for meta in self.meta_data:
                if meta.key == '_billing_wooccm11':
                    meta.value = value
                    return
        else:
            self.meta_data = []
        self.meta_data.append(MetaDatum(id=None, key='_billing_wooccm11', value=value))

    def set_meta_siret(self, value: str):
        if self.meta_data:
            for meta in self.meta_data:
                if meta.key == '_billing_wooccm12':
                    meta.value = value
                    return
        else:
            self.meta_data = []
        self.meta_data.append(MetaDatum(id=None, key='_billing_wooccm12', value=value))
