"""Modèle de données pour la réponse de l'API WooCommerce lors de la récup client."""
# generated by datamodel-codegen:
#   filename:  customer_get.json
#   timestamp: 2026-05-12T16:45:41+00:00

from __future__ import annotations

from typing import Any
from enum import Enum
from pydantic import BaseModel, Field


class Billing(BaseModel):
    """Données de facturation du client."""
    first_name: str
    last_name: str
    company: str
    address_1: str
    address_2: str
    city: str
    state: str
    postcode: str
    country: str
    email: str
    phone: str


class Shipping(BaseModel):
    """Données de livraison du client."""
    first_name: str
    last_name: str
    company: str
    address_1: str
    address_2: str
    city: str
    state: str
    postcode: str
    country: str


class MetaDatum(BaseModel):
    """Données méta du client."""
    id: int | None
    key: str
    value: str | CustomerType = ""


class CustomerType(str, Enum):
    """Types de clients."""
    part = "Particulier"    # pylint: disable=invalid-name
    pro = "Professionnel"   # pylint: disable=invalid-name


class SelfItem(BaseModel):
    """Lien vers l'objet lui-même."""
    href: str


class CollectionItem(BaseModel):
    """Lien vers la collection d'objets."""
    href: str


class FieldLinks(BaseModel):
    """Liens associés à l'objet."""
    self: list[SelfItem]
    collection: list[CollectionItem]


class WooCustomerGet(BaseModel):
    """
    Modèle de données pour la réponse de l'API WooCommerce lors de la récupération d'un client.
    Ce modèle inclut les informations de base du client, les adresses de facturation et
    de livraison, les données méta, et les liens associés à l'objet.
    """
    id: int
    date_created: str
    date_created_gmt: str
    date_modified: str
    date_modified_gmt: str
    email: str
    first_name: str
    last_name: str
    role: str
    username: str
    billing: Billing
    shipping: Shipping
    is_paying_customer: bool
    avatar_url: str
    meta_data: list[MetaDatum]
    field_links: FieldLinks = Field(..., alias='_links')

    def set_meta_type(self, value: str | CustomerType):
        """Met à jour ou ajoute la donnée méta pour le type de client."""
        for meta in self.meta_data:
            if meta.key == '_billing_wooccm10':
                meta.value = value
                return
        self.meta_data.append(MetaDatum(id=None, key='_billing_wooccm10', value=value))

    def set_meta_rs(self, value: str):
        """Met à jour ou ajoute la donnée méta pour le nom de l'entreprise."""
        for meta in self.meta_data:
            if meta.key == '_billing_wooccm11':
                meta.value = value
                return
        self.meta_data.append(MetaDatum(id=None, key='_billing_wooccm11', value=value))

    def set_meta_siret(self, value: str):
        """Met à jour ou ajoute la donnée méta pour le numéro SIRET."""
        for meta in self.meta_data:
            if meta.key == '_billing_wooccm12':
                meta.value = value
                return
        self.meta_data.append(MetaDatum(id=None, key='_billing_wooccm12', value=value))

    def get_customer_type(self) -> str:
        """Retourne le type de client."""
        return next(
            (meta.value for meta in self.meta_data if meta.key == '_billing_wooccm10'), ""
        ).lower()

    def get_company_name(self) -> str:
        """Retourne le nom de l'entreprise du client."""
        return next(
            (meta.value for meta in self.meta_data if meta.key == '_billing_wooccm11'), ""
        )

    def get_siret_number(self) -> str:
        """Retourne le numéro SIRET ou le RNA du client."""
        return next(
            (meta.value for meta in self.meta_data if meta.key == '_billing_wooccm12'), ""
        )

    def same_address(self, billing: Billing, shipping: Shipping) -> bool:
        """Vérifie si les adresses de facturation et de livraison sont identiques."""
        fields = ["address_1", "address_2", "city", "state", "postcode", "country"]

        b = billing.model_dump()
        s = shipping.model_dump()

        return all(b[f] == s[f] for f in fields)


    def to_dict_for_erp(self) -> dict[str, Any]:
        """Convertit les données du client en un format structuré pour l'ERP.
        Cette méthode organise les données du client en sections distinctes pour faciliter
        l'intégration avec l'ERP, en séparant les informations de base, les données spécifiques
        aux clients professionnels, les données spécifiques aux clients particuliers, les
        informations de contact, et les adresses. Elle prend également en compte les cas où
        les adresses de facturation et de livraison sont identiques pour éviter les redondances.
        """
        customer = {
            'wpwc_id': self.id,
            'customer_type': self.get_customer_type(),
        }
        if self.get_customer_type() == 'professionnel':
            pro = {
                'company_name': self.get_company_name(),
                'siret_number': self.get_siret_number()
            }
            part = {}
        else:
            part = {
                'first_name': self.first_name,
                'last_name': self.last_name,
            }
            pro = {}
        mail = {
            'email_name': 'Email WooCommerce',
            'email': self.email,
        }
        phone = {
            'phone_name': 'Téléphone WooCommerce',
            'phone': self.billing.phone,
        }
        if self.same_address(self.billing, self.shipping):
            address = [{
                'address_name': 'Adresse de facturation et livraison WooCommerce',
                'address_line1': self.billing.address_1,
                'address_line2': self.billing.address_2,
                'postal_code': self.billing.postcode,
                'city': self.billing.city,
                'state': self.billing.state,
                'country': self.billing.country,
                'is_billing': True,
                'is_shipping': True,
            }]
        else:
            address_billing = {
                'address_name': 'Adresse de facturation WooCommerce',
                'address_line1': self.billing.address_1,
                'address_line2': self.billing.address_2,
                'postal_code': self.billing.postcode,
                'city': self.billing.city,
                'state': self.billing.state,
                'country': self.billing.country,
                'is_billing': True,
                'is_shipping': False,
            }
            address_shipping = {
                'address_name': 'Adresse de livraison WooCommerce',
                'address_line1': self.shipping.address_1,
                'address_line2': self.shipping.address_2,
                'postal_code': self.shipping.postcode,
                'city': self.shipping.city,
                'state': self.shipping.state,
                'country': self.shipping.country,
                'is_billing': False,
                'is_shipping': True,
            }
            address = [address_billing, address_shipping]
        return {
            "customer": customer,
            "customer_part": part,
            "customer_pro": pro,
            "customer_mail": mail,
            "customer_phone": phone,
            "customer_address": address,
        }
