"""Module contenant les modèles de données pour la mise à jour des clients WooCommerce."""
# generated by datamodel-codegen:
#   filename:  customer_put.json
#   timestamp: 2026-05-12T16:46:22+00:00

from __future__ import annotations

from enum import Enum
from pydantic import BaseModel


class Billing(BaseModel):
    """
    Données de facturation du client.
    Attr:
    - first_name (str | None): Prénom du client.
    - last_name (str | None): Nom du client.
    - company (str | None): Société du client.
    - address_1 (str | None): Adresse 1 du client.
    - address_2 (str | None): Adresse 2 du client.
    - city (str | None): Ville du client.
    - state (str | None): État du client.
    - postcode (str | None): Code postal du client.
    - country (str | None): Pays du client.
    - email (str): Email du client.
    - phone (str | None): Téléphone du client.
    """
    first_name: str | None = None
    last_name: str | None = None
    company: str | None = None
    address_1: str | None = None
    address_2: str | None = None
    city: str | None = None
    state: str | None = None
    postcode: str | None = None
    country: str | None = None
    email: str
    phone: str | None = None


class Shipping(BaseModel):
    """
    Données de livraison du client.
    Attr:
    - first_name (str | None): Prénom du destinataire.
    - last_name (str | None): Nom du destinataire.
    - company (str | None): Société du destinataire.
    - address_1 (str | None): Adresse 1 du destinataire.
    - address_2 (str | None): Adresse 2 du destinataire.
    - city (str | None): Ville du destinataire.
    - state (str | None): État du destinataire.
    - postcode (str | None): Code postal du destinataire.
    - country (str | None): Pays du destinataire.
    """
    first_name: str | None = None
    last_name: str | None = None
    company: str | None = None
    address_1: str | None = None
    address_2: str | None = None
    city: str | None = None
    state: str | None = None
    postcode: str | None = None
    country: str | None = None


class MetaDatum(BaseModel):
    """
    Donnée de métadonnée pour un client WooCommerce.
    Attr:
    - id (int | None): ID de la métadonnée (généralement None lors de la création).
    - key (str): Clé de la métadonnée.
    - value (str | CustomerType | None): Valeur de la métadonnée, (chaîne ou un type de client).
    """
    id: int | None = None
    key: str
    value: str | CustomerType | None = None


class CustomerType(str, Enum):
    """
    Types de clients pour WooCommerce.
    Attr:
    - part (str): Client particulier.
    - pro (str): Client professionnel.
    """
    part = "Particulier"    # pylint: disable=invalid-name
    pro = "Professionnel"   # pylint: disable=invalid-name


class WCCustomerPut(BaseModel):
    """
    Modèle de données pour la mise à jour d'un client WooCommerce.
    Attr:
    - email (str): Email du client.
    - first_name (str | None): Prénom du client.
    - last_name (str | None): Nom du client.
    - username (str | None): Nom d'utilisateur du client.
    - billing (Billing | None): Informations de facturation du client.
    - shipping (Shipping | None): Informations de livraison du client.
    - meta_data (list[MetaDatum] | None): Métadonnées du client.
    """
    email: str
    first_name: str | None = None
    last_name: str | None = None
    username: str | None = None
    billing: Billing | None = None
    shipping: Shipping | None = None
    meta_data: list[MetaDatum] | None = None

    def set_meta_type(self, value: str | CustomerType):
        """
        Met à jour ou ajoute la métadonnée du type de client.
        Args:
            value (str | CustomerType): La valeur à définir pour le type de client.
        """
        if self.meta_data:
            for meta in self.meta_data:
                if meta.key == '_billing_wooccm10':
                    meta.value = value
                    return
        else:
            self.meta_data = []
        self.meta_data.append(MetaDatum(id=None, key='_billing_wooccm10', value=value))

    def set_meta_rs(self, value: str):
        """
        Met à jour ou ajoute la métadonnée du nom de la société (raison sociale).
        Args:
            value (str): La valeur à définir pour la raison sociale du client.
        """
        if self.meta_data:
            for meta in self.meta_data:
                if meta.key == '_billing_wooccm11':
                    meta.value = value
                    return
        else:
            self.meta_data = []
        self.meta_data.append(MetaDatum(id=None, key='_billing_wooccm11', value=value))

    def set_meta_siret(self, value: str):
        """
        Met à jour ou ajoute la métadonnée du numéro SIRET.
        Args:
            value (str): La valeur à définir pour le numéro SIRET du client.
        """
        if self.meta_data:
            for meta in self.meta_data:
                if meta.key == '_billing_wooccm12':
                    meta.value = value
                    return
        else:
            self.meta_data = []
        self.meta_data.append(MetaDatum(id=None, key='_billing_wooccm12', value=value))
