# ------------------------------------------------------------------------------
# --- Configuration page de connexion
# ------------------------------------------------------------------------------
# Paramètres
[params]
styles = ["css/login.css", "css/base.css"]
scripts = ["js/login.js", "js/base.js"]
# Clées
[meta]
title = "Connexion | Intranet"
description = "Page de connexion à l'intranet"
keywords = "connexion, login, intranet"
author = "Rémi Verschuur"
robots = "noindex, nofollow"
[meta.accessibility]
lang="fr"
direction="ltr"
aria_role="form"
# Pages spécifiques
[layout]
main_layout = "index.html"
# Flags
[flags]
navbar = false
searchbar = false