# Configuration des pages de l'application. Annuaire des pages.
[links]
home = "home.toml"
dashboard = "dashboard.toml"
login = "user/login.toml"
stock = "stock.toml"
register = "user/register.toml"
change_password = "user/change_password.toml"
modify = "user/modify.toml"
customer_index = "customer/index.toml"
customer_search = "customer/search.toml"
customer_create = "customer/create.toml"
customer_view = "customer/view.toml"
inventory = "inventory.toml"
stock_index = "stock/index.toml"
stock_references = "stock/references.toml"
stock_search = "stock/search.toml"
stock_order = "stock/order.toml"
stock_reservations = "stock/reservations.toml"
stock_council = "stock/council.toml"
supplier = "supplier.toml"
admin_index = "admin.toml"
admin_vat = "admin/vat.toml"
admin_users = "admin/users.toml"
admin_logs = "admin/logs.toml"

# ------------------------------------------------------------------------------
# --- Configuration par défaut si la page n'est pas trouvée
# ------------------------------------------------------------------------------
# Paramètres
[default.params]
tab = "Accueil"
styles = ["css/main.css"]
scripts = ["js/main.js"]
# Clées
[default.meta]
title = "Sauvetage | Intranet"
description = "Application de gestion de la librairie en ligne Editions du Sauvetage"
keywords = "sauvetage, intranet, gestion, librairie"
author = "Rémi Verschuur"
robots = "noindex, nofollow"
[default.meta.accessibility]
lang="fr"
direction="ltr"
aria_role="main"
# Pages spécifiques
[default.layout]
main_layout = "index.html"
extend_layout = ""
# Flags
[default.flags]
userbar = false
navbar = false
searchbar = false