services:
  db:
    image: mariadb:10.6
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - dbs_data:/var/lib/mysql
    networks:
      - wps_net

  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wp_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wp_buyer:/var/www/html/wp-content
      - wp_core:/var/www/html
    networks:
      - wps_net

  webserver:
    image: nginx:alpine
    container_name: wp_nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - wp_buyer:/var/www/html/wp-content
      - type: volume
        source: wp_core
        target: /var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./ssl:/etc/nginx/ssl:Z
    networks:
      - wps_net

  backup:
    build:
      context: .
      dockerfile: backup/Dockerfile
    container_name: wp_backup
    restart: unless-stopped
    depends_on:
      - db
      - wordpress
    env_file:
      - .env
    volumes:
      - wp_buyer:/var/www/html/wp-content:ro
      - ./backups:/backups
      - ./backup_logs:/var/log/backup
      - ./.env:/etc/backup/.env:ro
      - ./ssh:/root/.ssh:ro
    networks:
      - wps_net

volumes:
  dbs_data:
  wp_buyer:
  wp_core:

networks:
  wps_net:
