# ------------------------------------------------------------------------------
# --- Configuration page de changement de mot de passe
# ------------------------------------------------------------------------------
# Paramètres
[params]
styles = ["css/user/register.css", "css/main.css"]
scripts = ["js/user/chg_pwd.js", "js/main.js"]
# Clées
[meta]
title = "Changement de mot de passe | Intranet"
description = "Page de changement de mot de passe utilisateur à l'intranet"
keywords = "changement, mot de passe, intranet"
author = "Rémi Verschuur"
robots = "noindex, nofollow"
[meta.accessibility]
lang="fr"
direction="ltr"
aria_role="form"
# Pages spécifiques
[layout]
main_layout = "user/chg_pwd.html"
extend_layout = "index.html"
# Flags
[flags]
navbar = false
searchbar = false