[NotificationType]
01 = "Création"
02 = "Notifaction avancée"
03 = "Notification confirmée"
05 = "Suppression"
[ReasonForDeletion]
01 = "Réservé à Dilicom - Changement de distribution, nouveau titre."
03 = "Abandon de parution."
04 = "Erreur de référencement."
06 = "Décision de justice."
07 = "Retiré du catalogue."
08 = "Produit soldé."
[ProductIdentifier.ProductIDType]
01 = "Propriétaire (référence interne fournisseur)."
03 = "GTIN-13"
15 = "ISBN-13"
31 = "Référence notice BNF"
35 = "Lien vers notice BNF"
[BarcodeComposite.BarcodeType]
02 = "True"
00 = "False"
[DescriptiveDetail.ProductComposition]
00 = "Produit simple."
10 = "Produit composé."
11 = "Collection mutli-produits."
20 = "Vente B2B."
30 = "Lot B2B."
31 = "Lot Professionnel sécable."
[DescriptiveDetail.ProductForm]
AB = "Cassette Audio"
AC = "CD Audio"
AM = "Disque Vinyle"
BB = "Relié"
BC = "Broché/Poche"
BG = "Cuirs et belles reliures"
CA = "Cartes routières - Non spécifiées"
CB = "Cartes routières - Pliées"
CE = "Globes et planisphères"
DB = "CD-ROM"
FC = "Diapositives"
PK = "Posters"
VI = "DVD Vidéo"
VJ = "VHS Vidéo"
XA = "B2B - PLV"
ZE = "Jeux (sauf jeux vidéo)"
[DescriptiveDetail.Measure.MeasureType]
01 = "Hauteur"
02 = "Largeur"
03 = "Epaisseur"
08 = "Poids"
[DescriptiveDetail.Measure.MeasureUnitCode]
cm = "Centimètre"
mm = "Millimètre"
gr = "Gramme"
kg = "Kilogramme"
[DescriptiveDetail.TitleDetail.TitleType]
01 = "Titre complet"
05 = "Libellé caisse (20 car.)"
10 = "Libellé standard (30 car.)"
[DescriptiveDetail.Contributor.ContributorRole]
A01 = "Auteur"
