[invoices]
service = "invoices"

[invoices.documentation]
api_url_prod = "https://www.zohoapis.com/invoice/v3"
description = "An invoice is a statement of items sold by a seller. It includes all the details of sale including units of goods, price of goods sold, shipping details, etc."

[invoices.documentation.return_codes]
"1001" = "Invoice Number already exist"
"1002" = "Contact Person does not exist"
"3009" = "The contact details of this invoice cannot be edited as the credits have been applied to it"
"3010" = "The customer for this invoice cannot be changed because payments have been recorded for this invoice"
"4001" = "Payments have been recorded for these invoices. Hence they cannot be deleted"
"12008" = "This invoice has credits applied to it. Hence, it cannot be deleted"

[[invoices.documentation.methods]]
for = "Create an invoice"
endpoint = "/invoices"
type = "POST"
parameters.needed = ["organization_id"]
parameters.optional = []

[invoices.documentation.methods.response]
invoice_id = "obligatory"
status = "obligatory"

[[invoices.documentation.methods]]
for = "Get an invoice"
endpoint = "/invoices/{invoice_id}"
type = "GET"
parameters.needed = ["invoice_id", "organization_id"]
parameters.optional = []

[invoices.documentation.methods.response]
invoice_details = "obligatory"

[[invoices.documentation.methods]]
for = "Update an invoice"
endpoint = "/invoices/{invoice_id}"
type = "PUT"
parameters.needed = ["invoice_id", "organization_id"]
parameters.optional = []

[invoices.documentation.methods.response]
status = "obligatory"

[[invoices.documentation.methods]]
for = "Delete an invoice"
endpoint = "/invoices/{invoice_id}"
type = "DELETE"
parameters.needed = ["invoice_id", "organization_id"]
parameters.optional = []

[invoices.documentation.methods.response]
status = "obligatory"

[[invoices.documentation.methods]]
for = "Send an invoice"
endpoint = "/invoices/{invoice_id}/email"
type = "POST"
parameters.needed = ["invoice_id", "organization_id"]
parameters.optional = []

[invoices.documentation.methods.response]
status = "obligatory"

[[invoices.documentation.methods]]
for = "Get invoice templates"
endpoint = "/invoices/templates"
type = "GET"
parameters.needed = ["organization_id"]
parameters.optional = []

[invoices.documentation.methods.response]
templates = "obligatory"