global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true

ping:
  entryPoint: web

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
      trustedIPs:
        - "10.89.0.0/16"
        - "192.168.1.0/24"
  
  websecure:
    address: ":443"
    http:
      tls: {}
    forwardedHeaders:
      insecure: true
      trustedIPs:
        - "10.89.0.0/16"
        - "192.168.1.0/24"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: contact@editions-sauvetage.fr
      storage: /app/pki/acme.json
      httpChallenge:
        entryPoint: web

tls:
  certificates:
    - certFile: /app/pki/server-cert.pem
      keyFile: /app/pki/server-key.pem

log:
  level: INFO
  format: json