"""Modèle de données pour la mise à jour d'une commande WooCommerce."""
# generated by datamodel-codegen:
#   filename:  order_put.json
#   timestamp: 2026-05-12T17:15:35+00:00

from __future__ import annotations

from pydantic import BaseModel


class Billing(BaseModel):
    """
    Données de facturation du client.
    Attr:
    - first_name (str | None): Prénom du client.
    - last_name (str | None): Nom du client.
    - address_1 (str | None): Adresse 1 du client.
    - address_2 (str | None): Adresse 2 du client.
    - city (str | None): Ville du client.
    - state (str | None): État du client.
    - postcode (str | None): Code postal du client.
    - country (str | None): Pays du client.
    - email (str): Email du client.
    - phone (str | None): Téléphone du client.
    """
    first_name: str | None = None
    last_name: str | None = None
    address_1: str | None = None
    address_2: str | None = None
    city: str | None = None
    state: str | None = None
    postcode: str | None = None
    country: str | None = None
    email: str
    phone: str | None = None


class Shipping(BaseModel):
    """
    Données de livraison du client.
    Attr:
    - first_name (str | None): Prénom du destinataire.
    - last_name (str | None): Nom du destinataire.
    - address_1 (str | None): Adresse 1 du destinataire.
    - address_2 (str | None): Adresse 2 du destinataire.
    - city (str | None): Ville du destinataire.
    - state (str | None): État du destinataire.
    - postcode (str | None): Code postal du destinataire.
    - country (str | None): Pays du destinataire.
    """
    first_name: str | None = None
    last_name: str | None = None
    address_1: str | None = None
    address_2: str | None = None
    city: str | None = None
    state: str | None = None
    postcode: str | None = None
    country: str | None = None


class LineItem(BaseModel):
    """
    Données d'une ligne de commande.
    Attr:
    - product_id (int | None): ID du produit.
    - quantity (int | None): Quantité commandée.
    - variation_id (int | None): ID de la variation du produit, si applicable.
    """
    product_id: int | None = None
    quantity: int | None = None
    variation_id: int | None = None


class ShippingLine(BaseModel):
    """
    Données d'une ligne de livraison.
    Attr:
    - method_id (str | None): ID de la méthode de livraison.
    - method_title (str | None): Titre de la méthode de livraison.
    - total (str | None): Coût total de la livraison.
    """
    method_id: str | None = None
    method_title: str | None = None
    total: str | None = None


class WCOrderPut(BaseModel):
    """
    Modèle de données pour la mise à jour d'une commande WooCommerce.
    Attr:
    - payment_method (str | None): Méthode de paiement utilisée pour la commande.
    - payment_method_title (str | None): Titre de la méthode de paiement.
    - set_paid (bool | None): Indique si la commande est payée ou non.
    - billing (Billing | None): Données de facturation du client.
    - shipping (Shipping | None): Données de livraison du client.
    - line_items (list[LineItem] | None): Liste des lignes de commande.
    - shipping_lines (list[ShippingLine] | None): Liste des lignes de livraison.
    """
    payment_method: str | None = None
    payment_method_title: str | None = None
    set_paid: bool | None = None
    billing: Billing | None = None
    shipping: Shipping | None = None
    line_items: list[LineItem] | None = None
    shipping_lines: list[ShippingLine] | None = None
