# generated by datamodel-codegen:
#   filename:  order_get.json
#   timestamp: 2026-05-12T17:15:52+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Billing(BaseModel):
    first_name: str
    last_name: str
    company: str
    address_1: str
    address_2: str
    city: str
    state: str
    postcode: str
    country: str
    email: str
    phone: str


class Shipping(BaseModel):
    first_name: str
    last_name: str
    company: str
    address_1: str
    address_2: str
    city: str
    state: str
    postcode: str
    country: str


class MetaDatum(BaseModel):
    id: int
    key: str
    value: str


class Tax(BaseModel):
    id: int
    total: str
    subtotal: str


class LineItem(BaseModel):
    id: int
    name: str
    product_id: int
    variation_id: int
    quantity: int
    tax_class: str
    subtotal: str
    subtotal_tax: str
    total: str
    total_tax: str
    taxes: list[Tax]
    meta_data: list[MetaDatum]
    sku: str
    price: int


class TaxLine(BaseModel):
    id: int
    rate_code: str
    rate_id: int
    label: str
    compound: bool
    tax_total: str
    shipping_tax_total: str
    meta_data: list[Any]


class ShippingLine(BaseModel):
    id: int
    method_title: str
    method_id: str
    total: str
    total_tax: str
    taxes: list[Any]
    meta_data: list[Any]


class SelfItem(BaseModel):
    href: str


class CollectionItem(BaseModel):
    href: str


class FieldLinks(BaseModel):
    self: list[SelfItem]
    collection: list[CollectionItem]


class Model(BaseModel):
    id: int
    parent_id: int
    number: str
    order_key: str
    created_via: str
    version: str
    status: str
    currency: str
    date_created: str
    date_created_gmt: str
    date_modified: str
    date_modified_gmt: str
    discount_total: str
    discount_tax: str
    shipping_total: str
    shipping_tax: str
    cart_tax: str
    total: str
    total_tax: str
    prices_include_tax: bool
    customer_id: int
    customer_ip_address: str
    customer_user_agent: str
    customer_note: str
    billing: Billing
    shipping: Shipping
    payment_method: str
    payment_method_title: str
    transaction_id: str
    date_paid: str
    date_paid_gmt: str
    date_completed: None
    date_completed_gmt: None
    cart_hash: str
    meta_data: list[MetaDatum]
    line_items: list[LineItem]
    tax_lines: list[TaxLine]
    shipping_lines: list[ShippingLine]
    fee_lines: list[Any]
    coupon_lines: list[Any]
    refunds: list[Any]
    field_links: FieldLinks = Field(..., alias='_links')
