# generated by datamodel-codegen:
#   filename:  order_put.json
#   timestamp: 2026-05-12T17:15:35+00:00

from __future__ import annotations

from pydantic import BaseModel


class Billing(BaseModel):
    first_name: str | None = None
    last_name: str | None = None
    address_1: str | None = None
    address_2: str | None = None
    city: str | None = None
    state: str | None = None
    postcode: str | None = None
    country: str | None = None
    email: str
    phone: str | None = None


class Shipping(BaseModel):
    first_name: str | None = None
    last_name: str | None = None
    address_1: str | None = None
    address_2: str | None = None
    city: str | None = None
    state: str | None = None
    postcode: str | None = None
    country: str | None = None


class LineItem(BaseModel):
    product_id: int | None = None
    quantity: int | None = None
    variation_id: int | None = None


class ShippingLine(BaseModel):
    method_id: str | None = None
    method_title: str | None = None
    total: str | None = None


class Model(BaseModel):
    payment_method: str | None = None
    payment_method_title: str | None = None
    set_paid: bool | None = None
    billing: Billing | None = None
    shipping: Shipping | None = None
    line_items: list[LineItem] | None = None
    shipping_lines: list[ShippingLine] | None = None
