"""Modèle de données pour représenter une commande récupérée depuis l'API WooCommerce."""
# generated by datamodel-codegen:
#   filename:  order_get.json
#   timestamp: 2026-05-12T17:15:52+00:00

from __future__ import annotations

from typing import Any
from datetime import datetime, timezone

from pydantic import BaseModel, Field

SITE_WEB = "Site Web"


class Billing(BaseModel):
    """
    Informations de facturation d'une commande.
    Attributs:
    - first_name (str): Prénom du client.
    - last_name (str): Nom de famille du client.
    - company (str): Nom de l'entreprise du client (si applicable).
    - address_1 (str): Adresse de facturation ligne 1.
    - address_2 (str): Adresse de facturation ligne 2 (si applicable).
    - city (str): Ville de facturation.
    - state (str): État ou province de facturation.
    - postcode (str): Code postal de facturation.
    - country (str): Pays de facturation.
    - email (str): Adresse e-mail du client.
    - phone (str): Numéro de téléphone du client.
    """
    first_name: str
    last_name: str
    company: str
    address_1: str
    address_2: str
    city: str
    state: str
    postcode: str
    country: str
    email: str
    phone: str


class Shipping(BaseModel):
    """
    Informations de livraison d'une commande.
    Attributs:
    - first_name (str): Prénom du destinataire.
    - last_name (str): Nom de famille du destinataire.
    - company (str): Nom de l'entreprise du destinataire (si applicable).
    - address_1 (str): Adresse de livraison ligne 1.
    - address_2 (str): Adresse de livraison ligne 2 (si applicable).
    - city (str): Ville de livraison.
    - state (str): État ou province de livraison.
    - postcode (str): Code postal de livraison.
    - country (str): Pays de livraison.
    """
    first_name: str
    last_name: str
    company: str
    address_1: str
    address_2: str
    city: str
    state: str
    postcode: str
    country: str


class MetaDatum(BaseModel):
    """
    Métadonnée associée à une commande ou à un élément de commande.
    Attributs:
    - id (int): Identifiant unique de la métadonnée.
    - key (str): Clé de la métadonnée.
    - value (str): Valeur de la métadonnée.
    """
    id: int
    key: str
    value: str


class Tax(BaseModel):
    """
    Informations sur la taxe d'une commande.
    Attributs:
    - id (int): Identifiant unique de la taxe.
    - total (str): Montant total de la taxe.
    - subtotal (str): Montant de la taxe avant application des réductions.
    """
    id: int
    total: str
    subtotal: str


class LineItem(BaseModel):
    """
    Informations sur un élément de ligne d'une commande.
    Attributs:
    - id (int): Identifiant unique de l'élément de ligne.
    - name (str): Nom du produit ou de la variation.
    - product_id (int): Identifiant du produit associé à cet élément de ligne.
    - variation_id (int): Identifiant de la variation du produit (si applicable).
    - quantity (int): Quantité commandée de cet élément de ligne.
    - tax_class (str): Classe de taxe associée à cet élément de ligne.
    - subtotal (str): Montant total de cet élément de ligne avant application des réductions.
    - subtotal_tax (str): Montant de la taxe pour cet élément de ligne avant réductions.
    - total (str): Montant total de cet élément de ligne après application des réductions.
    - total_tax (str): Montant de la taxe pour cet élément de ligne après réductions.
    - taxes (list[Tax]): Liste des taxes associées à cet élément de ligne.
    - meta_data (list[MetaDatum]): Liste des métadonnées associées à cet élément de ligne.
    - sku (str): Référence SKU du produit ou de la variation.
    - price (int): Prix unitaire de cet élément de ligne.
    """
    id: int
    name: str
    product_id: int
    variation_id: int
    quantity: int
    tax_class: str
    subtotal: str
    subtotal_tax: str
    total: str
    total_tax: str
    taxes: list[Tax]
    meta_data: list[MetaDatum]
    sku: str
    price: int


class TaxLine(BaseModel):
    """
    Informations sur une ligne de taxe d'une commande.
    Attributs:
    - id (int): Identifiant unique de la ligne de taxe.
    - rate_code (str): Code de taux de la taxe.
    - rate_id (int): Identifiant du taux de la taxe.
    - label (str): Libellé de la taxe.
    - compound (bool): Indique si la taxe est composée ou non.
    - tax_total (str): Montant total de la taxe.
    - shipping_tax_total (str): Montant total de la taxe sur la livraison.
    - meta_data (list[Any]): Liste des métadonnées associées à cette ligne de taxe.
    """
    id: int
    rate_code: str
    rate_id: int
    label: str
    compound: bool
    tax_total: str
    shipping_tax_total: str
    meta_data: list[Any]


class ShippingLine(BaseModel):
    """
    Informations sur une ligne de livraison d'une commande.
    Attributs:
    - id (int): Identifiant unique de la ligne de livraison.
    - method_title (str): Titre de la méthode de livraison.
    - method_id (str): Identifiant de la méthode de livraison.
    - total (str): Montant total de la livraison.
    - total_tax (str): Montant total de la taxe sur la livraison.
    - taxes (list[Any]): Liste des taxes associées à cette ligne de livraison.
    - meta_data (list[Any]): Liste des métadonnées associées à cette ligne de livraison.
    """
    id: int
    method_title: str
    method_id: str
    total: str
    total_tax: str
    taxes: list[Any]
    meta_data: list[Any]


class SelfItem(BaseModel):
    """
    Lien vers la ressource elle-même dans l'API WooCommerce.
    Attributs:
    - href (str): URL de la ressource.
    """
    href: str


class CollectionItem(BaseModel):
    """
    Lien vers une collection de ressources dans l'API WooCommerce.
    Attributs:
    - href (str): URL de la collection.
    """
    href: str


class FieldLinks(BaseModel):
    """
    Liens hypermédia associés à une ressource dans l'API WooCommerce.
    Attributs:
    - self (list[SelfItem]): Liste de liens vers la ressource elle-même.
    - collection (list[CollectionItem]): Liste de liens vers la collection de ressources.
    """
    self: list[SelfItem]
    collection: list[CollectionItem]


class WCOrderGet(BaseModel):
    """
    Modèle de données représentant une commande récupérée depuis l'API WooCommerce.
    Attributs:
    - id (int): Identifiant unique de la commande.
    - parent_id (int): Identifiant de la commande parente (si applicable).
    - number (str): Numéro de la commande.
    - order_key (str): Clé de la commande utilisée pour les opérations d'API.
    - created_via (str): Méthode utilisée pour créer la commande (ex: 'checkout', 'admin').
    - version (str): Version de l'API utilisée pour créer la commande.
    - status (str): Statut actuel de la commande (ex: 'processing', 'completed').
    - currency (str): Devise utilisée pour la commande (ex: 'USD').
    - date_created (str): Date de création de la commande au format ISO 8601.
    - date_created_gmt (str): Date de création de la commande en GMT au format ISO 8601.
    - date_modified (str): Date de dernière modification de la commande au format ISO 8601.
    - date_modified_gmt (str): Date GMT de dernière modification de la commande au format ISO 8601.
    - discount_total (str): Montant total des réductions appliquées à la commande.
    - discount_tax (str): Montant total des taxes sur les réductions appliquées à la commande.
    - shipping_total (str): Montant total des frais de livraison pour la commande.
    - shipping_tax (str): Montant total des taxes sur les frais de livraison pour la commande.
    - cart_tax (str): Montant total des taxes sur les articles du panier pour la commande.
    - total (str): Montant total de la commande après réductions et ajout des frais de livraison.
    - total_tax (str): Montant total des taxes pour la commande.
    - prices_include_tax (bool): Indique si les prix de la commande incluent les taxes ou non.
    - customer_id (int): Identifiant du client associé à la commande.
    - customer_ip_address (str): Adresse IP du client au moment de la commande.
    - customer_user_agent (str): User agent du client au moment de la commande.
    - customer_note (str): Note laissée par le client lors de la commande.
    - billing (Billing): Informations de facturation associées à la commande.
    - shipping (Shipping): Informations de livraison associées à la commande.
    - payment_method (str): Méthode de paiement utilisée pour la commande.
    - payment_method_title (str): Titre de la méthode de paiement utilisée pour la commande.
    - transaction_id (str): Identifiant de la transaction de paiement associée à la commande.
    - date_paid (str): Date de paiement de la commande au format ISO 8601.
    - date_paid_gmt (str): Date de paiement de la commande en GMT au format ISO 8601.
    - date_completed (None): Date de complétion de la commande (si applicable) au format ISO 8601.
    - date_completed_gmt (None): Date GMT de complétion de la commande au format ISO 8601.
    - cart_hash (str): Hash du panier utilisé pour la commande.
    - meta_data (list[MetaDatum]): Liste des métadonnées associées à la commande.
    - line_items (list[LineItem]): Liste des éléments de ligne associés à la commande.
    - tax_lines (list[TaxLine]): Liste des lignes de taxe associées à la commande.
    - shipping_lines (list[ShippingLine]): Liste des lignes de livraison associées à la commande.
    - fee_lines (list[Any]): Liste des lignes de frais associées à la commande.
    - coupon_lines (list[Any]): Liste des lignes de coupons associées à la commande.
    - refunds (list[Any]): Liste des remboursements associés à la commande.
    - field_links (FieldLinks): Liens hypermédia associés à la commande dans l'API WooCommerce.
    """
    id: int
    parent_id: int
    number: str
    order_key: str
    created_via: str
    version: str
    status: str
    currency: str
    date_created: str
    date_created_gmt: str
    date_modified: str
    date_modified_gmt: str
    discount_total: str
    discount_tax: str
    shipping_total: str
    shipping_tax: str
    cart_tax: str
    total: str
    total_tax: str
    prices_include_tax: bool
    customer_id: int
    customer_ip_address: str
    customer_user_agent: str
    customer_note: str
    billing: Billing
    shipping: Shipping
    payment_method: str
    payment_method_title: str
    transaction_id: str
    date_paid: str
    date_paid_gmt: str
    date_completed: None
    date_completed_gmt: None
    cart_hash: str
    meta_data: list[MetaDatum]
    line_items: list[LineItem]
    tax_lines: list[TaxLine]
    shipping_lines: list[ShippingLine]
    fee_lines: list[Any]
    coupon_lines: list[Any]
    refunds: list[Any]
    field_links: FieldLinks = Field(..., alias='_links')

    def get_customer_id(self) -> int:
        """Retourne l'identifiant du client associé à la commande."""
        return self.customer_id

    def get_total_amount(self) -> str:
        """Retourne le montant total de la commande."""
        return self.total

    def _get_discount_amount(self, line_item) -> str:
        return str(float(line_item.subtotal) - float(line_item.total))

    def _get_vat_rate(self, line_item) -> float:
        return float(line_item.total_tax) / float(line_item.total) \
            if float(line_item.total) > 0 else 0

    def get_wpwc_product_id(self, line_item) -> int:
        """Retourne l'identifiant du produit WooCommerce pour un élément de ligne donné."""
        return line_item.product_id

    def to_dict_for_erp_order(self) -> dict[str, Any]:
        """Convertit l'objet WCOrderGet en un dictionnaire adapté pour l'ERP."""
        return {
            "wpwc_id": self.id,
            "status": "draft",
            "create_source": SITE_WEB,
            "created_at": self.date_created,
            "update_source": SITE_WEB,
            "updated_at": self.date_modified,
            "last_synced_at": datetime.now(timezone.utc).isoformat(),
        }

    def to_dict_for_erp_orderline(self, line_item) -> dict[str, Any]:
        """
        Convertit une ligne de la commande en un dictionnaire adapté pour l'ERP.
        """
        return {

                "wpwc_id": line_item.id,
                "quantity": line_item.quantity,
                "status": "draft",
                "unit_price": line_item.price,
                "discount": self._get_discount_amount(line_item),
                "vat_rate": self._get_vat_rate(line_item),
                "create_source": SITE_WEB,
                "created_at": self.date_created,
                "update_source": SITE_WEB,
                "updated_at": self.date_modified,
            }
