FROM python:3.12-slim-bookworm

WORKDIR /app
ENV PYTHONPATH=/app

COPY app_front/ app_front/
COPY db_models/ db_models/
COPY logs/ logs/

# Rendre le script entrypoint exécutable
RUN pip install --no-cache-dir -r app_front/requirements.txt \
    && chmod +x app_front/entrypoint.sh

ENTRYPOINT [ "app_front/entrypoint.sh" ]
