FROM docker.io/library/python:3.12-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    netcat-openbsd \
    curl \
    wget \
    libmagic1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV PYTHONPATH=/app

COPY app_front/ app_front/
COPY db_models/ db_models/
COPY logs/ logs/
COPY config/__init__.py config/__init__.py
COPY config/logs/ config/logs/

# Rendre le script entrypoint exécutable
RUN pip install -r app_front/requirements.txt \
    && chmod +x app_front/entrypoint.sh

ENTRYPOINT [ "app_front/entrypoint.sh" ]
