FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../db_models ../db_models
COPY . /app/

ENTRYPOINT [ "gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app" ]
