"""modification de conception pour les images

Revision ID: a004401f83fb
Revises: a1b2c3d4e5f6
Create Date: 2026-05-11 16:08:16.292529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a004401f83fb'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_access_tokens',
    sa.Column('token', sa.String(), nullable=False, comment="Nom du fichier image (UUID.webp) — sert d'identifiant de jeton"),
    sa.Column('valid_from', sa.DateTime(), nullable=False, comment='Date de création du jeton'),
    sa.Column('valid_until', sa.DateTime(), nullable=False, comment="Date d'expiration du jeton (valid_from + 1 heure)"),
    sa.Column('used_at', sa.DateTime(), nullable=True, comment='Date de consommation du jeton (None = pas encore utilisé)'),
    sa.PrimaryKeyConstraint('token'),
    schema='app_schema'
    )
    op.create_table('order_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Commande associée'),
    sa.Column('external_id', sa.String(length=100), nullable=True, comment='ID de la commande dans le système externe'),
    sa.Column('external_system', sa.String(length=50), nullable=False, comment='Système externe : wpwc, …'),
    sa.Column('sync_direction', sa.String(length=20), nullable=False, comment='Direction : inbound, outbound'),
    sa.Column('operation', sa.String(length=20), nullable=False, comment='Opération : create, update, delete'),
    sa.Column('sync_status', sa.String(length=20), nullable=False, comment='Statut : success, failed, pending'),
    sa.Column('error_message', sa.Text(), nullable=True, comment="Message d'erreur en cas d'échec"),
    sa.Column('synced_at', sa.DateTime(), nullable=False, comment='Date et heure de la synchronisation'),
    sa.ForeignKeyConstraint(['order_id'], ['app_schema.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('invoice_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False, comment='Facture associée'),
    sa.Column('external_id', sa.String(length=100), nullable=True, comment='ID de la facture dans le système externe (ex : ID Henrri)'),
    sa.Column('external_system', sa.String(length=50), nullable=False, comment='Système externe : henrri, …'),
    sa.Column('sync_direction', sa.String(length=20), nullable=False, comment='Direction : inbound, outbound'),
    sa.Column('operation', sa.String(length=20), nullable=False, comment='Opération : create, update, delete'),
    sa.Column('sync_status', sa.String(length=20), nullable=False, comment='Statut : success, failed, pending'),
    sa.Column('error_message', sa.Text(), nullable=True, comment="Message d'erreur en cas d'échec"),
    sa.Column('synced_at', sa.DateTime(), nullable=False, comment='Date et heure de la synchronisation'),
    sa.ForeignKeyConstraint(['invoice_id'], ['app_schema.invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.drop_constraint(op.f('books_general_object_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_addresses_customer_id_fkey'), 'customer_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'customer_addresses', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_mails_customer_id_fkey'), 'customer_mails', type_='foreignkey')
    op.create_foreign_key(None, 'customer_mails', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_parts_customer_id_fkey'), 'customer_parts', type_='foreignkey')
    op.create_foreign_key(None, 'customer_parts', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_phones_customer_id_fkey'), 'customer_phones', type_='foreignkey')
    op.create_foreign_key(None, 'customer_phones', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('customer_pros_customer_id_fkey'), 'customer_pros', type_='foreignkey')
    op.create_foreign_key(None, 'customer_pros', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.add_column('customer_sync_logs', sa.Column('operation', sa.String(length=20), nullable=False, comment='Opération : create, update, delete'))
    op.alter_column('customer_sync_logs', 'sync_direction',
               existing_type=sa.VARCHAR(length=20),
               comment='Direction : inbound, outbound',
               existing_nullable=False)
    op.alter_column('customer_sync_logs', 'sync_status',
               existing_type=sa.VARCHAR(length=20),
               comment='Statut : success, failed, pending',
               existing_nullable=False)
    op.drop_constraint(op.f('customer_sync_logs_customer_id_fkey'), 'customer_sync_logs', type_='foreignkey')
    op.create_foreign_key(None, 'customer_sync_logs', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_column('customer_sync_logs', 'sync_source')
    op.drop_constraint(op.f('dilicom_referential_ean13_fkey'), 'dilicom_referential', type_='foreignkey')
    op.drop_constraint(op.f('dilicom_referential_gln13_fkey'), 'dilicom_referential', type_='foreignkey')
    op.create_foreign_key(None, 'dilicom_referential', 'general_objects', ['ean13'], ['ean13'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'dilicom_referential', 'suppliers', ['gln13'], ['gln13'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('general_objects_vat_rate_id_fkey'), 'general_objects', type_='foreignkey')
    op.drop_constraint(op.f('general_objects_supplier_id_fkey'), 'general_objects', type_='foreignkey')
    op.create_foreign_key(None, 'general_objects', 'suppliers', ['supplier_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'general_objects', 'vat_rates', ['vat_rate_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('inventory_movements_general_object_id_fkey'), 'inventory_movements', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_movements', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('invoice_lines_invoice_id_fkey'), 'invoice_lines', type_='foreignkey')
    op.drop_constraint(op.f('invoice_lines_order_line_id_fkey'), 'invoice_lines', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_lines', 'invoices', ['invoice_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'invoice_lines', 'order_lines', ['order_line_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('invoices_order_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'orders', ['order_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.add_column('media_files', sa.Column('is_local', sa.Boolean(), nullable=False, comment='Indique si le fichier est stocké localement sur le volume'))
    op.alter_column('media_files', 'file_link',
               existing_type=sa.VARCHAR(),
               comment='Lien vers le fichier média (URL externe ou nom de fichier local)',
               existing_comment='Lien vers le fichier média ext.',
               existing_nullable=True)
    op.drop_constraint(op.f('media_files_general_object_id_fkey'), 'media_files', type_='foreignkey')
    op.create_foreign_key(None, 'media_files', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_column('media_files', 'file_data')
    op.drop_constraint(op.f('obj_metadatas_general_object_id_fkey'), 'obj_metadatas', type_='foreignkey')
    op.create_foreign_key(None, 'obj_metadatas', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.add_column('object_sync_logs', sa.Column('external_id', sa.String(length=100), nullable=True, comment="ID de l'entité dans le système externe (ex : WooCommerce)"))
    op.add_column('object_sync_logs', sa.Column('external_system', sa.String(length=50), nullable=False, comment='Système externe : wpwc, henrri, …'))
    op.add_column('object_sync_logs', sa.Column('sync_direction', sa.String(length=20), nullable=False, comment='Direction : inbound, outbound'))
    op.alter_column('object_sync_logs', 'operation',
               existing_type=sa.VARCHAR(length=20),
               comment='Opération : create, update, delete, batch',
               existing_comment='Opération : create, update, delete',
               existing_nullable=False)
    op.drop_column('object_sync_logs', 'wpwc_id')
    op.drop_constraint(op.f('object_tags_general_object_id_fkey'), 'object_tags', type_='foreignkey')
    op.drop_constraint(op.f('object_tags_tag_id_fkey'), 'object_tags', type_='foreignkey')
    op.create_foreign_key(None, 'object_tags', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'object_tags', 'tags', ['tag_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('order_in_supplier_id_fkey'), 'order_in', type_='foreignkey')
    op.create_foreign_key(None, 'order_in', 'suppliers', ['supplier_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('order_in_lines_order_in_id_fkey'), 'order_in_lines', type_='foreignkey')
    op.drop_constraint(op.f('order_in_lines_inventory_movement_id_fkey'), 'order_in_lines', type_='foreignkey')
    op.drop_constraint(op.f('order_in_lines_general_object_id_fkey'), 'order_in_lines', type_='foreignkey')
    op.create_foreign_key(None, 'order_in_lines', 'order_in', ['order_in_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'order_in_lines', 'inventory_movements', ['inventory_movement_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'order_in_lines', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('order_lines_order_id_fkey'), 'order_lines', type_='foreignkey')
    op.drop_constraint(op.f('order_lines_general_object_id_fkey'), 'order_lines', type_='foreignkey')
    op.create_foreign_key(None, 'order_lines', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'order_lines', 'orders', ['order_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('orders_delivery_address_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_customer_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_invoice_address_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'orders', 'customer_addresses', ['delivery_address_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'orders', 'customer_addresses', ['invoice_address_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('other_objects_general_object_id_fkey'), 'other_objects', type_='foreignkey')
    op.create_foreign_key(None, 'other_objects', 'general_objects', ['general_object_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('shipment_lines_order_line_id_fkey'), 'shipment_lines', type_='foreignkey')
    op.drop_constraint(op.f('shipment_lines_shipment_id_fkey'), 'shipment_lines', type_='foreignkey')
    op.create_foreign_key(None, 'shipment_lines', 'shipments', ['shipment_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.create_foreign_key(None, 'shipment_lines', 'order_lines', ['order_line_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    op.drop_constraint(op.f('shipments_order_id_fkey'), 'shipments', type_='foreignkey')
    op.create_foreign_key(None, 'shipments', 'orders', ['order_id'], ['id'], source_schema='app_schema', referent_schema='app_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('shipments_order_id_fkey'), 'shipments', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'shipment_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'shipment_lines', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('shipment_lines_shipment_id_fkey'), 'shipment_lines', 'shipments', ['shipment_id'], ['id'])
    op.create_foreign_key(op.f('shipment_lines_order_line_id_fkey'), 'shipment_lines', 'order_lines', ['order_line_id'], ['id'])
    op.drop_constraint(None, 'other_objects', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('other_objects_general_object_id_fkey'), 'other_objects', 'general_objects', ['general_object_id'], ['id'])
    op.drop_constraint(None, 'orders', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('orders_invoice_address_id_fkey'), 'orders', 'customer_addresses', ['invoice_address_id'], ['id'])
    op.create_foreign_key(op.f('orders_customer_id_fkey'), 'orders', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('orders_delivery_address_id_fkey'), 'orders', 'customer_addresses', ['delivery_address_id'], ['id'])
    op.drop_constraint(None, 'order_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'order_lines', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('order_lines_general_object_id_fkey'), 'order_lines', 'general_objects', ['general_object_id'], ['id'])
    op.create_foreign_key(op.f('order_lines_order_id_fkey'), 'order_lines', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_in_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'order_in_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'order_in_lines', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('order_in_lines_general_object_id_fkey'), 'order_in_lines', 'general_objects', ['general_object_id'], ['id'])
    op.create_foreign_key(op.f('order_in_lines_inventory_movement_id_fkey'), 'order_in_lines', 'inventory_movements', ['inventory_movement_id'], ['id'])
    op.create_foreign_key(op.f('order_in_lines_order_in_id_fkey'), 'order_in_lines', 'order_in', ['order_in_id'], ['id'])
    op.drop_constraint(None, 'order_in', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('order_in_supplier_id_fkey'), 'order_in', 'suppliers', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'object_tags', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'object_tags', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('object_tags_tag_id_fkey'), 'object_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('object_tags_general_object_id_fkey'), 'object_tags', 'general_objects', ['general_object_id'], ['id'])
    op.add_column('object_sync_logs', sa.Column('wpwc_id', sa.INTEGER(), autoincrement=False, nullable=True, comment="ID de l'entité dans WooCommerce"))
    op.alter_column('object_sync_logs', 'operation',
               existing_type=sa.VARCHAR(length=20),
               comment='Opération : create, update, delete',
               existing_comment='Opération : create, update, delete, batch',
               existing_nullable=False)
    op.drop_column('object_sync_logs', 'sync_direction')
    op.drop_column('object_sync_logs', 'external_system')
    op.drop_column('object_sync_logs', 'external_id')
    op.drop_constraint(None, 'obj_metadatas', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('obj_metadatas_general_object_id_fkey'), 'obj_metadatas', 'general_objects', ['general_object_id'], ['id'])
    op.add_column('media_files', sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=True, comment='Données brutes du fichier média'))
    op.drop_constraint(None, 'media_files', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('media_files_general_object_id_fkey'), 'media_files', 'general_objects', ['general_object_id'], ['id'])
    op.alter_column('media_files', 'file_link',
               existing_type=sa.VARCHAR(),
               comment='Lien vers le fichier média ext.',
               existing_comment='Lien vers le fichier média (URL externe ou nom de fichier local)',
               existing_nullable=True)
    op.drop_column('media_files', 'is_local')
    op.drop_constraint(None, 'invoices', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_order_id_fkey'), 'invoices', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'invoice_lines', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'invoice_lines', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_lines_order_line_id_fkey'), 'invoice_lines', 'order_lines', ['order_line_id'], ['id'])
    op.create_foreign_key(op.f('invoice_lines_invoice_id_fkey'), 'invoice_lines', 'invoices', ['invoice_id'], ['id'])
    op.drop_constraint(None, 'inventory_movements', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_movements_general_object_id_fkey'), 'inventory_movements', 'general_objects', ['general_object_id'], ['id'])
    op.drop_constraint(None, 'general_objects', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'general_objects', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('general_objects_supplier_id_fkey'), 'general_objects', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(op.f('general_objects_vat_rate_id_fkey'), 'general_objects', 'vat_rates', ['vat_rate_id'], ['id'])
    op.drop_constraint(None, 'dilicom_referential', schema='app_schema', type_='foreignkey')
    op.drop_constraint(None, 'dilicom_referential', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('dilicom_referential_gln13_fkey'), 'dilicom_referential', 'suppliers', ['gln13'], ['gln13'])
    op.create_foreign_key(op.f('dilicom_referential_ean13_fkey'), 'dilicom_referential', 'general_objects', ['ean13'], ['ean13'])
    op.add_column('customer_sync_logs', sa.Column('sync_source', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customer_sync_logs', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_sync_logs_customer_id_fkey'), 'customer_sync_logs', 'customers', ['customer_id'], ['id'])
    op.alter_column('customer_sync_logs', 'sync_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Statut : success, failed, pending',
               existing_nullable=False)
    op.alter_column('customer_sync_logs', 'sync_direction',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Direction : inbound, outbound',
               existing_nullable=False)
    op.drop_column('customer_sync_logs', 'operation')
    op.drop_constraint(None, 'customer_pros', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_pros_customer_id_fkey'), 'customer_pros', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_phones', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_phones_customer_id_fkey'), 'customer_phones', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_parts', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_parts_customer_id_fkey'), 'customer_parts', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_mails', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_mails_customer_id_fkey'), 'customer_mails', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_addresses', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('customer_addresses_customer_id_fkey'), 'customer_addresses', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'books', schema='app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('books_general_object_id_fkey'), 'books', 'general_objects', ['general_object_id'], ['id'])
    op.drop_table('invoice_sync_logs', schema='app_schema')
    op.drop_table('order_sync_logs', schema='app_schema')
    op.drop_table('media_access_tokens', schema='app_schema')
    # ### end Alembic commands ###
