# ------------------------------------------------------------------------------
# --- Configuration page d'accueil                                           ---
# ------------------------------------------------------------------------------
# Paramètres
[params]
tab = "Stock"
styles = [
    "css/main.css",
    "css/stock/council.css"
]
scripts = ["js/main.js"]
# Clées
[meta]
title = "Stock | Intranet"
description = "Page de gestion du conseil de stock de l'intranet Sauvetage"
keywords = "stock, conseil, intranet"
author = "Rémi Verschuur"
robots = "noindex, nofollow"
[meta.accessibility]
lang="fr"
direction="ltr"
aria_role="main"
# Pages spécifiques
[layout]
main_layout = "stock/council.html"
extend_layout = "index.html"
# Flags pour afficher ou non les éléments sur les commons
[flags]
navbar = true
searchbar = false
userbar = true
