# ------------------------------------------------------------------------------
# --- Configuration page de commande entrante                                ---
# ------------------------------------------------------------------------------
# Paramètres
[params]
tab = "Stock"
styles = [
    "css/main.css",
    "css/stock/order.css"
]
scripts = [
    "js/main.js",
]
# Clées
[meta]
title = "Stock | Intranet"
description = "Page de gestion des commandes entrantes de l'intranet Sauvetage"
keywords = "stock, commande, intranet"
author = "Rémi Verschuur"
robots = "noindex, nofollow"
[meta.accessibility]
lang="fr"
direction="ltr"
aria_role="main"
# Pages spécifiques
[layout]
main_layout = "stock/order.html"
extend_layout = "index.html"
# Flags pour afficher ou non les éléments sur les commons
[flags]
navbar = true
searchbar = false
userbar = true
htmx = true
