"""Migration initiale users

Revision ID: 4079c3f664ca
Revises:
Create Date: 2026-02-16 12:56:06.955233

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4079c3f664ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',    # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment="Identifiant unique de l'utilisateur"),
        sa.Column('username', sa.String(), nullable=False,
                  comment="Nom d'utilisateur"),
        sa.Column('email', sa.String(), nullable=False,
                  comment="Adresse email de l'utilisateur"),
        sa.Column('is_active', sa.Boolean(), nullable=False,
                  comment='Utilisateur actif ?'),
        sa.Column('nb_failed_logins', sa.Integer(), nullable=False,
                  comment='Nombre de tentatives de connexion échouées'),
        sa.Column('is_locked', sa.Boolean(), nullable=False,
                  comment="Compte de l'utilisateur verrouillé ?"),
        sa.Column('permissions', sa.String(), nullable=False,
                  comment="Permissions de l'utilisateur"),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment="Date de création de l'utilisateur"),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment="Date de dernière MàJ de l'utilisateur"),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username'),
        schema='auth_schema'
    )
    op.create_table('users_passwords',  # pylint: disable=no-member
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False,
                  comment='Identifiant unique du mot de passe'),
        sa.Column('user_id', sa.Integer(), nullable=False,
                  comment="Identifiant de l'utilisateur associé"),
        sa.Column('password_hash', sa.String(), nullable=False,
                  comment="Hash du mot de passe de l'utilisateur"),
        sa.Column('from_date', sa.DateTime(), nullable=False,
                  comment='Date de début de validité du mot de passe'),
        sa.Column('to_date', sa.DateTime(), nullable=True,
                  comment='Date fin de validité du mot de passe'),
        sa.Column('created_at', sa.DateTime(), nullable=False,
                  comment='Date de création du mot de passe'),
        sa.Column('updated_at', sa.DateTime(), nullable=False,
                  comment='Date de dernière MàJ du mot de passe'),
        sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'],
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='auth_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_passwords', schema='auth_schema')  # pylint: disable=no-member
    op.drop_table('users', schema='auth_schema')    # pylint: disable=no-member
    # ### end Alembic commands ###
