"""verification de session cote serveur

Revision ID: 76256cebd162
Revises: a544e3310379
Create Date: 2026-08-20 07:58:14.958592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76256cebd162'
down_revision: Union[str, Sequence[str], None] = 'a544e3310379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique de la session'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='Empreinte SHA-256 du jeton de session'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment="Identifiant de l'utilisateur associé"),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment="Date d'expiration absolue de la session"),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False, comment='Date de dernière activité de la session'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Date de révocation de la session'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Date de création de la session'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='auth_schema'
    )
    op.create_index(op.f('ix_auth_schema_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False, schema='auth_schema')
    op.drop_constraint(op.f('users_passwords_user_id_fkey'), 'users_passwords', type_='foreignkey')
    op.create_foreign_key(None, 'users_passwords', 'users', ['user_id'], ['id'], source_schema='auth_schema', referent_schema='auth_schema', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_passwords', schema='auth_schema', type_='foreignkey')
    op.create_foreign_key(op.f('users_passwords_user_id_fkey'), 'users_passwords', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_auth_schema_user_sessions_user_id'), table_name='user_sessions', schema='auth_schema')
    op.drop_table('user_sessions', schema='auth_schema')
    # ### end Alembic commands ###
